#include "rf_phreaker/lte_layer_3_decoder/asn_type_descriptor.h"

//asn_DEF_BCCH_DL_SCH_Message.name;
//asn_DEF_SystemInformationBlockType1;
//asn_DEF_SystemInformationBlockType2;
//asn_DEF_SystemInformationBlockType3;
//asn_DEF_SystemInformationBlockType4;
//asn_DEF_SystemInformationBlockType5;
//asn_DEF_SystemInformationBlockType6;
//asn_DEF_SystemInformationBlockType7;
//asn_DEF_SystemInformationBlockType8;
//asn_DEF_SystemInformationBlockType9;
//asn_DEF_SystemInformationBlockType10;
//asn_DEF_SystemInformationBlockType11;
//

asn_TYPE_descriptor_t      asn_DEF_BCCH_BCH_Message;
asn_TYPE_descriptor_t      asn_DEF_MasterInformationBlock;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType1;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType2;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType3;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType4;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType5;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType5bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType6;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType7;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType11;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType11bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType12;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType13;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType13_1;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType13_2;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType13_3;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType13_4;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType14;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_1bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_2;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_2bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_2ter;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_3;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_3bis;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_4;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_5;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_6;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_7;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType15_8;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType16;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType17;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType18;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType19;
asn_TYPE_descriptor_t      asn_DEF_SysInfoType20;
asn_TYPE_descriptor_t      asn_DEF_SysInfoTypeSB1;
asn_TYPE_descriptor_t      asn_DEF_SysInfoTypeSB2;