/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_CellsToAddModUTRA_FDD_H_
#define	_CellsToAddModUTRA_FDD_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/lte_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/lte_rrc_asn_library/PhysCellIdUTRA-FDD.h"
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellsToAddModUTRA-FDD */
typedef struct CellsToAddModUTRA_FDD {
	long	 cellIndex;
	PhysCellIdUTRA_FDD_t	 physCellId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellsToAddModUTRA_FDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellsToAddModUTRA_FDD;

#ifdef __cplusplus
}
#endif

#endif	/* _CellsToAddModUTRA_FDD_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
