/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_CellReselectionParametersCDMA2000_r11_H_
#define	_CellReselectionParametersCDMA2000_r11_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/lte_rrc_asn_library/BandClassListCDMA2000.h"
#include "rf_phreaker/lte_rrc_asn_library/T-Reselection.h"
#include <rf_phreaker/lte_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE_OF.h>
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SpeedStateScaleFactors;
struct NeighCellCDMA2000_r11;

/* CellReselectionParametersCDMA2000-r11 */
typedef struct CellReselectionParametersCDMA2000_r11 {
	BandClassListCDMA2000_t	 bandClassList;
	struct CellReselectionParametersCDMA2000_r11__neighCellList_r11 {
		A_SEQUENCE_OF(struct NeighCellCDMA2000_r11) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} neighCellList_r11;
	T_Reselection_t	 t_ReselectionCDMA2000;
	struct SpeedStateScaleFactors	*t_ReselectionCDMA2000_SF	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellReselectionParametersCDMA2000_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellReselectionParametersCDMA2000_r11;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/lte_rrc_asn_library/SpeedStateScaleFactors.h"
#include "rf_phreaker/lte_rrc_asn_library/NeighCellCDMA2000-r11.h"

#endif	/* _CellReselectionParametersCDMA2000_r11_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
