/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_InDeviceCoexIndication_r11_IEs_H_
#define	_InDeviceCoexIndication_r11_IEs_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/lte_rrc_asn_library/OCTET_STRING.h>
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AffectedCarrierFreqList_r11;
struct TDM_AssistanceInfo_r11;

/* InDeviceCoexIndication-r11-IEs */
typedef struct InDeviceCoexIndication_r11_IEs {
	struct AffectedCarrierFreqList_r11	*affectedCarrierFreqList_r11	/* OPTIONAL */;
	struct TDM_AssistanceInfo_r11	*tdm_AssistanceInfo_r11	/* OPTIONAL */;
	OCTET_STRING_t	*lateNonCriticalExtension	/* OPTIONAL */;
	struct InDeviceCoexIndication_r11_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InDeviceCoexIndication_r11_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InDeviceCoexIndication_r11_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/lte_rrc_asn_library/AffectedCarrierFreqList-r11.h"
#include "rf_phreaker/lte_rrc_asn_library/TDM-AssistanceInfo-r11.h"

#endif	/* _InDeviceCoexIndication_r11_IEs_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
