/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MeasSubframePatternConfigNeigh_r10_H_
#define	_MeasSubframePatternConfigNeigh_r10_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/lte_rrc_asn_library/NULL.h>
#include "rf_phreaker/lte_rrc_asn_library/MeasSubframePattern-r10.h"
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/lte_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasSubframePatternConfigNeigh_r10_PR {
	MeasSubframePatternConfigNeigh_r10_PR_NOTHING,	/* No components present */
	MeasSubframePatternConfigNeigh_r10_PR_release,
	MeasSubframePatternConfigNeigh_r10_PR_setup
} MeasSubframePatternConfigNeigh_r10_PR;

/* Forward declarations */
struct MeasSubframeCellList_r10;

/* MeasSubframePatternConfigNeigh-r10 */
typedef struct MeasSubframePatternConfigNeigh_r10 {
	MeasSubframePatternConfigNeigh_r10_PR present;
	union MeasSubframePatternConfigNeigh_r10_u {
		NULL_t	 release;
		struct MeasSubframePatternConfigNeigh_r10__setup {
			MeasSubframePattern_r10_t	 measSubframePatternNeigh_r10;
			struct MeasSubframeCellList_r10	*measSubframeCellList_r10	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasSubframePatternConfigNeigh_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasSubframePatternConfigNeigh_r10;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/lte_rrc_asn_library/MeasSubframeCellList-r10.h"

#endif	/* _MeasSubframePatternConfigNeigh_r10_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
