/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_MultiBandInfo_v9e0_H_
#define	_MultiBandInfo_v9e0_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/lte_rrc_asn_library/FreqBandIndicator-v9e0.h"
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MultiBandInfo-v9e0 */
typedef struct MultiBandInfo_v9e0 {
	FreqBandIndicator_v9e0_t	*freqBandIndicator_v9e0	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiBandInfo_v9e0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiBandInfo_v9e0;

#ifdef __cplusplus
}
#endif

#endif	/* _MultiBandInfo_v9e0_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
