/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "EUTRA-RRC-Definitions.asn"
 * 	`asn1c -fcompound-names -pdu=all`
 */

#ifndef	_RACH_ConfigCommonSCell_r11_H_
#define	_RACH_ConfigCommonSCell_r11_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/lte_rrc_asn_library/PowerRampingParameters.h"
#include "rf_phreaker/lte_rrc_asn_library/PreambleTransMax.h"
#include <rf_phreaker/lte_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RACH-ConfigCommonSCell-r11 */
typedef struct RACH_ConfigCommonSCell_r11 {
	PowerRampingParameters_t	 powerRampingParameters_r11;
	struct RACH_ConfigCommonSCell_r11__ra_SupervisionInfo_r11 {
		PreambleTransMax_t	 preambleTransMax_r11;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ra_SupervisionInfo_r11;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RACH_ConfigCommonSCell_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RACH_ConfigCommonSCell_r11;

#ifdef __cplusplus
}
#endif

#endif	/* _RACH_ConfigCommonSCell_r11_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
