/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../asn1/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -fcompound-names -fnative-types`
 */

#ifndef	_STAG_Id_r11_H_
#define	_STAG_Id_r11_H_


#include <rf_phreaker/lte_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/lte_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* STAG-Id-r11 */
typedef long	 STAG_Id_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_STAG_Id_r11;
asn_struct_free_f STAG_Id_r11_free;
asn_struct_print_f STAG_Id_r11_print;
asn_constr_check_f STAG_Id_r11_constraint;
ber_type_decoder_f STAG_Id_r11_decode_ber;
der_type_encoder_f STAG_Id_r11_encode_der;
xer_type_decoder_f STAG_Id_r11_decode_xer;
xer_type_encoder_f STAG_Id_r11_encode_xer;
per_type_decoder_f STAG_Id_r11_decode_uper;
per_type_encoder_f STAG_Id_r11_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _STAG_Id_r11_H_ */
#include <rf_phreaker/lte_rrc_asn_library/asn_internal.h>
