/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_ACK_NACK_repetitionFactor_H_
#define	_ACK_NACK_repetitionFactor_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ACK-NACK-repetitionFactor */
typedef long	 ACK_NACK_repetitionFactor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ACK_NACK_repetitionFactor;
asn_struct_free_f ACK_NACK_repetitionFactor_free;
asn_struct_print_f ACK_NACK_repetitionFactor_print;
asn_constr_check_f ACK_NACK_repetitionFactor_constraint;
ber_type_decoder_f ACK_NACK_repetitionFactor_decode_ber;
der_type_encoder_f ACK_NACK_repetitionFactor_encode_der;
xer_type_decoder_f ACK_NACK_repetitionFactor_decode_xer;
xer_type_encoder_f ACK_NACK_repetitionFactor_encode_xer;
per_type_decoder_f ACK_NACK_repetitionFactor_decode_uper;
per_type_encoder_f ACK_NACK_repetitionFactor_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ACK_NACK_repetitionFactor_H_ */
