/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_AvailableMinimumSF_VCAM_H_
#define	_AvailableMinimumSF_VCAM_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MinimumSpreadingFactor.h"
#include "rf_phreaker/umts_rrc_asn_library/NF-Max.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxAvailablePCPCH-Number.h"
#include "rf_phreaker/umts_rrc_asn_library/AvailableAP-Signature-VCAMList.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AvailableMinimumSF-VCAM */
typedef struct AvailableMinimumSF_VCAM {
	MinimumSpreadingFactor_t	 minimumSpreadingFactor;
	NF_Max_t	 nf_Max;
	MaxAvailablePCPCH_Number_t	 maxAvailablePCPCH_Number;
	AvailableAP_Signature_VCAMList_t	 availableAP_Signature_VCAMList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AvailableMinimumSF_VCAM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AvailableMinimumSF_VCAM;

#ifdef __cplusplus
}
#endif

#endif	/* _AvailableMinimumSF_VCAM_H_ */
