/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CD_AccessSlotSubchannel_H_
#define	_CD_AccessSlotSubchannel_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CD-AccessSlotSubchannel */
typedef long	 CD_AccessSlotSubchannel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CD_AccessSlotSubchannel;
asn_struct_free_f CD_AccessSlotSubchannel_free;
asn_struct_print_f CD_AccessSlotSubchannel_print;
asn_constr_check_f CD_AccessSlotSubchannel_constraint;
ber_type_decoder_f CD_AccessSlotSubchannel_decode_ber;
der_type_encoder_f CD_AccessSlotSubchannel_encode_der;
xer_type_decoder_f CD_AccessSlotSubchannel_decode_xer;
xer_type_encoder_f CD_AccessSlotSubchannel_encode_xer;
per_type_decoder_f CD_AccessSlotSubchannel_decode_uper;
per_type_encoder_f CD_AccessSlotSubchannel_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CD_AccessSlotSubchannel_H_ */
