/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CellChangeOrderFromUTRAN_v590ext_IEs_H_
#define	_CellChangeOrderFromUTRAN_v590ext_IEs_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/GERAN-SystemInformation.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR {
	CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR_NOTHING,	/* No components present */
	CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR_sI,
	CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR_pSI
} CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR;

/* CellChangeOrderFromUTRAN-v590ext-IEs */
typedef struct CellChangeOrderFromUTRAN_v590ext_IEs {
	struct CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType {
		CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_PR present;
		union CellChangeOrderFromUTRAN_v590ext_IEs__geran_SystemInfoType_u {
			GERAN_SystemInformation_t	 sI;
			GERAN_SystemInformation_t	 pSI;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *geran_SystemInfoType;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellChangeOrderFromUTRAN_v590ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellChangeOrderFromUTRAN_v590ext_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _CellChangeOrderFromUTRAN_v590ext_IEs_H_ */
