/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CellAndChannelIdentity_H_
#define	_CellAndChannelIdentity_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/BurstType.h"
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftLong.h"
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber.h"
#include "rf_phreaker/umts_rrc_asn_library/CellParametersID.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellAndChannelIdentity */
typedef struct CellAndChannelIdentity {
	BurstType_t	 burstType;
	MidambleShiftLong_t	 midambleShift;
	TimeslotNumber_t	 timeslot;
	CellParametersID_t	 cellParametersID;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellAndChannelIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellAndChannelIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _CellAndChannelIdentity_H_ */
