/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CellSelectReselectInfoTreselectionScaling_v5c0ext_H_
#define	_CellSelectReselectInfoTreselectionScaling_v5c0ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/SpeedDependentScalingFactor.h"
#include "rf_phreaker/umts_rrc_asn_library/TreselectionScalingFactor.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct T_CRMax;

/* CellSelectReselectInfoTreselectionScaling-v5c0ext */
typedef struct CellSelectReselectInfoTreselectionScaling_v5c0ext {
	struct T_CRMax	*non_HCS_t_CR_Max	/* OPTIONAL */;
	SpeedDependentScalingFactor_t	*speedDependentScalingFactor	/* OPTIONAL */;
	TreselectionScalingFactor_t	*interFrequencyTreselectionScalingFactor	/* OPTIONAL */;
	TreselectionScalingFactor_t	*interRATTreselectionScalingFactor	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellSelectReselectInfoTreselectionScaling_v5c0ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellSelectReselectInfoTreselectionScaling_v5c0ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/T-CRMax.h"

#endif	/* _CellSelectReselectInfoTreselectionScaling_v5c0ext_H_ */
