/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CellUpdateCause_ext_H_
#define	_CellUpdateCause_ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellUpdateCause_ext {
	CellUpdateCause_ext_mbms_Reception	= 0,
	CellUpdateCause_ext_mbms_PTP_RB_Request	= 1,
	CellUpdateCause_ext_dummy	= 2,
	CellUpdateCause_ext_spare1	= 3
} e_CellUpdateCause_ext;

/* CellUpdateCause-ext */
typedef long	 CellUpdateCause_ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellUpdateCause_ext;
asn_struct_free_f CellUpdateCause_ext_free;
asn_struct_print_f CellUpdateCause_ext_print;
asn_constr_check_f CellUpdateCause_ext_constraint;
ber_type_decoder_f CellUpdateCause_ext_decode_ber;
der_type_encoder_f CellUpdateCause_ext_encode_der;
xer_type_decoder_f CellUpdateCause_ext_decode_xer;
xer_type_encoder_f CellUpdateCause_ext_encode_xer;
per_type_decoder_f CellUpdateCause_ext_decode_uper;
per_type_encoder_f CellUpdateCause_ext_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CellUpdateCause_ext_H_ */
