/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CID_InclusionInfo_r4_H_
#define	_CID_InclusionInfo_r4_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CID_InclusionInfo_r4 {
	CID_InclusionInfo_r4_pdcp_Header	= 0,
	CID_InclusionInfo_r4_rfc3095_PacketFormat	= 1
} e_CID_InclusionInfo_r4;

/* CID-InclusionInfo-r4 */
typedef long	 CID_InclusionInfo_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CID_InclusionInfo_r4;
asn_struct_free_f CID_InclusionInfo_r4_free;
asn_struct_print_f CID_InclusionInfo_r4_print;
asn_constr_check_f CID_InclusionInfo_r4_constraint;
ber_type_decoder_f CID_InclusionInfo_r4_decode_ber;
der_type_encoder_f CID_InclusionInfo_r4_encode_der;
xer_type_decoder_f CID_InclusionInfo_r4_decode_xer;
xer_type_encoder_f CID_InclusionInfo_r4_encode_xer;
per_type_decoder_f CID_InclusionInfo_r4_decode_uper;
per_type_encoder_f CID_InclusionInfo_r4_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CID_InclusionInfo_r4_H_ */
