/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_COUNT_CSingle_H_
#define	_COUNT_CSingle_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/CN-DomainIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* COUNT-CSingle */
typedef struct COUNT_CSingle {
	CN_DomainIdentity_t	 cn_DomainIdentity;
	BIT_STRING_t	 count_C;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} COUNT_CSingle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_COUNT_CSingle;

#ifdef __cplusplus
}
#endif

#endif	/* _COUNT_CSingle_H_ */
