/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CQI_DTX_Timer_H_
#define	_CQI_DTX_Timer_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CQI_DTX_Timer {
	CQI_DTX_Timer_sub_frames_0	= 0,
	CQI_DTX_Timer_sub_frames_1	= 1,
	CQI_DTX_Timer_sub_frames_2	= 2,
	CQI_DTX_Timer_sub_frames_4	= 3,
	CQI_DTX_Timer_sub_frames_8	= 4,
	CQI_DTX_Timer_sub_frames_16	= 5,
	CQI_DTX_Timer_sub_frames_32	= 6,
	CQI_DTX_Timer_sub_frames_64	= 7,
	CQI_DTX_Timer_sub_frames_128	= 8,
	CQI_DTX_Timer_sub_frames_256	= 9,
	CQI_DTX_Timer_sub_frames_512	= 10,
	CQI_DTX_Timer_sub_frames_Infinity	= 11,
	CQI_DTX_Timer_spare4	= 12,
	CQI_DTX_Timer_spare3	= 13,
	CQI_DTX_Timer_spare2	= 14,
	CQI_DTX_Timer_spare1	= 15
} e_CQI_DTX_Timer;

/* CQI-DTX-Timer */
typedef long	 CQI_DTX_Timer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CQI_DTX_Timer;
asn_struct_free_f CQI_DTX_Timer_free;
asn_struct_print_f CQI_DTX_Timer_print;
asn_constr_check_f CQI_DTX_Timer_constraint;
ber_type_decoder_f CQI_DTX_Timer_decode_ber;
der_type_encoder_f CQI_DTX_Timer_encode_der;
xer_type_decoder_f CQI_DTX_Timer_decode_xer;
xer_type_encoder_f CQI_DTX_Timer_encode_xer;
per_type_decoder_f CQI_DTX_Timer_decode_uper;
per_type_encoder_f CQI_DTX_Timer_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CQI_DTX_Timer_H_ */
