/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_CS_HSPA_Information_H_
#define	_CS_HSPA_Information_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UL-AMR-Rate.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxCS-Delay.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CS-HSPA-Information */
typedef struct CS_HSPA_Information {
	UL_AMR_Rate_t	*ul_AMR_Rate	/* OPTIONAL */;
	MaxCS_Delay_t	 maxCS_Delay;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CS_HSPA_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CS_HSPA_Information;

#ifdef __cplusplus
}
#endif

#endif	/* _CS_HSPA_Information_H_ */
