/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_DL_DPCH_InfoPerRL_PostFDD_H_
#define	_DL_DPCH_InfoPerRL_PostFDD_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/PCPICH-UsageForChannelEst.h"
#include "rf_phreaker/umts_rrc_asn_library/DL-ChannelisationCode.h"
#include "rf_phreaker/umts_rrc_asn_library/TPC-CombinationIndex.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DL-DPCH-InfoPerRL-PostFDD */
typedef struct DL_DPCH_InfoPerRL_PostFDD {
	PCPICH_UsageForChannelEst_t	 pCPICH_UsageForChannelEst;
	DL_ChannelisationCode_t	 dl_ChannelisationCode;
	TPC_CombinationIndex_t	 tpc_CombinationIndex;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_DPCH_InfoPerRL_PostFDD_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_DPCH_InfoPerRL_PostFDD;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_DPCH_InfoPerRL_PostFDD_H_ */
