/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_DL_LogicalChannelMapping_r5_H_
#define	_DL_LogicalChannelMapping_r5_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DL-TransportChannelType-r5.h"
#include "rf_phreaker/umts_rrc_asn_library/LogicalChannelIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DL-LogicalChannelMapping-r5 */
typedef struct DL_LogicalChannelMapping_r5 {
	DL_TransportChannelType_r5_t	 dl_TransportChannelType;
	LogicalChannelIdentity_t	*logicalChannelIdentity	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DL_LogicalChannelMapping_r5_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DL_LogicalChannelMapping_r5;

#ifdef __cplusplus
}
#endif

#endif	/* _DL_LogicalChannelMapping_r5_H_ */
