/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_DRAC_ClassIdentity_H_
#define	_DRAC_ClassIdentity_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DRAC-ClassIdentity */
typedef long	 DRAC_ClassIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRAC_ClassIdentity;
asn_struct_free_f DRAC_ClassIdentity_free;
asn_struct_print_f DRAC_ClassIdentity_print;
asn_constr_check_f DRAC_ClassIdentity_constraint;
ber_type_decoder_f DRAC_ClassIdentity_decode_ber;
der_type_encoder_f DRAC_ClassIdentity_encode_der;
xer_type_decoder_f DRAC_ClassIdentity_decode_xer;
xer_type_encoder_f DRAC_ClassIdentity_encode_xer;
per_type_decoder_f DRAC_ClassIdentity_decode_uper;
per_type_encoder_f DRAC_ClassIdentity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DRAC_ClassIdentity_H_ */
