/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_DRAC_StaticInformation_H_
#define	_DRAC_StaticInformation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TransmissionTimeValidity.h"
#include "rf_phreaker/umts_rrc_asn_library/TimeDurationBeforeRetry.h"
#include "rf_phreaker/umts_rrc_asn_library/DRAC-ClassIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DRAC-StaticInformation */
typedef struct DRAC_StaticInformation {
	TransmissionTimeValidity_t	 transmissionTimeValidity;
	TimeDurationBeforeRetry_t	 timeDurationBeforeRetry;
	DRAC_ClassIdentity_t	 drac_ClassIdentity;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRAC_StaticInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRAC_StaticInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _DRAC_StaticInformation_H_ */
