/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_DTX_Info_H_
#define	_DTX_Info_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UE-DTX-Cycle2InactivityThreshold.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/umts_rrc_asn_library/UE-DTX-long-preamble-length.h"
#include "rf_phreaker/umts_rrc_asn_library/MAC-InactivityThreshold.h"
#include "rf_phreaker/umts_rrc_asn_library/CQI-DTX-Timer.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-DPCCH-Burst.h"
#include "rf_phreaker/umts_rrc_asn_library/DTX-E-DCH-TTI-10ms.h"
#include "rf_phreaker/umts_rrc_asn_library/DTX-E-DCH-TTI-2ms.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DTX_Info__e_dch_TTI_Length_PR {
	DTX_Info__e_dch_TTI_Length_PR_NOTHING,	/* No components present */
	DTX_Info__e_dch_TTI_Length_PR_dtx_e_dch_TTI_10ms,
	DTX_Info__e_dch_TTI_Length_PR_dtx_e_dch_TTI_2ms
} DTX_Info__e_dch_TTI_Length_PR;

/* DTX-Info */
typedef struct DTX_Info {
	struct DTX_Info__e_dch_TTI_Length {
		DTX_Info__e_dch_TTI_Length_PR present;
		union DTX_Info__e_dch_TTI_Length_u {
			DTX_E_DCH_TTI_10ms_t	 dtx_e_dch_TTI_10ms;
			DTX_E_DCH_TTI_2ms_t	 dtx_e_dch_TTI_2ms;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} e_dch_TTI_Length;
	UE_DTX_Cycle2InactivityThreshold_t	 ue_dtx_cycle2InactivityThreshold;
	long	*ue_dtx_cycle2DefaultSG	/* OPTIONAL */;
	UE_DTX_long_preamble_length_t	*ue_dtx_long_preamble_length	/* OPTIONAL */;
	MAC_InactivityThreshold_t	 mac_InactivityThreshold;
	CQI_DTX_Timer_t	 cqi_dtx_Timer;
	UE_DPCCH_Burst_t	 ue_dpcch_Burst1;
	UE_DPCCH_Burst_t	 ue_dpcch_Burst2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DTX_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DTX_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _DTX_Info_H_ */
