/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_E_DCH_RL_InfoNewSecServingCell_H_
#define	_E_DCH_RL_InfoNewSecServingCell_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/E-AGCH-Information.h"
#include "rf_phreaker/umts_rrc_asn_library/E-RGCH-Information.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR {
	E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR_NOTHING,	/* No components present */
	E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR_e_RGCH_Information,
	E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR_releaseIndicator
} E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR;

/* Forward declarations */
struct E_HICH_Information;

/* E-DCH-RL-InfoNewSecServingCell */
typedef struct E_DCH_RL_InfoNewSecServingCell {
	E_AGCH_Information_t	 e_AGCH_Information;
	struct E_HICH_Information	*e_HICH_Information	/* OPTIONAL */;
	struct E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info {
		E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_PR present;
		union E_DCH_RL_InfoNewSecServingCell__e_RGCH_Info_u {
			E_RGCH_Information_t	 e_RGCH_Information;
			NULL_t	 releaseIndicator;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *e_RGCH_Info;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_DCH_RL_InfoNewSecServingCell_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_DCH_RL_InfoNewSecServingCell;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/E-HICH-Information.h"

#endif	/* _E_DCH_RL_InfoNewSecServingCell_H_ */
