/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_E_DCH_MAC_d_FlowPowerOffset_H_
#define	_E_DCH_MAC_d_FlowPowerOffset_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E-DCH-MAC-d-FlowPowerOffset */
typedef long	 E_DCH_MAC_d_FlowPowerOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_DCH_MAC_d_FlowPowerOffset;
asn_struct_free_f E_DCH_MAC_d_FlowPowerOffset_free;
asn_struct_print_f E_DCH_MAC_d_FlowPowerOffset_print;
asn_constr_check_f E_DCH_MAC_d_FlowPowerOffset_constraint;
ber_type_decoder_f E_DCH_MAC_d_FlowPowerOffset_decode_ber;
der_type_encoder_f E_DCH_MAC_d_FlowPowerOffset_encode_der;
xer_type_decoder_f E_DCH_MAC_d_FlowPowerOffset_decode_xer;
xer_type_encoder_f E_DCH_MAC_d_FlowPowerOffset_encode_xer;
per_type_decoder_f E_DCH_MAC_d_FlowPowerOffset_decode_uper;
per_type_encoder_f E_DCH_MAC_d_FlowPowerOffset_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_DCH_MAC_d_FlowPowerOffset_H_ */
