/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_E_DPDCH_SchedulingTransmConfiguration_H_
#define	_E_DPDCH_SchedulingTransmConfiguration_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E_DPDCH_SchedulingTransmConfiguration__servingGrant__primary_Secondary_GrantSelector {
	E_DPDCH_SchedulingTransmConfiguration__servingGrant__primary_Secondary_GrantSelector_primary	= 0,
	E_DPDCH_SchedulingTransmConfiguration__servingGrant__primary_Secondary_GrantSelector_secondary	= 1
} e_E_DPDCH_SchedulingTransmConfiguration__servingGrant__primary_Secondary_GrantSelector;

/* E-DPDCH-SchedulingTransmConfiguration */
typedef struct E_DPDCH_SchedulingTransmConfiguration {
	BIT_STRING_t	*ms2_SchedTransmGrantHARQAlloc	/* OPTIONAL */;
	struct E_DPDCH_SchedulingTransmConfiguration__servingGrant {
		long	 value;
		long	 primary_Secondary_GrantSelector;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *servingGrant;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_DPDCH_SchedulingTransmConfiguration_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_primary_Secondary_GrantSelector_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_E_DPDCH_SchedulingTransmConfiguration;

#ifdef __cplusplus
}
#endif

#endif	/* _E_DPDCH_SchedulingTransmConfiguration_H_ */
