/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_E_DPDCH_Info_r8_H_
#define	_E_DPDCH_Info_r8_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/E-TFCI-TableIndex.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DCH-MinimumSet-E-TFCI.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DPDCH-Reference-E-TFCIList-r7.h"
#include "rf_phreaker/umts_rrc_asn_library/MinReduced-E-DPDCH-GainFactor.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DPDCH-MaxChannelisationCodes.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DPDCH-PL-NonMax.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DPDCH-SchedulingInfoConfiguration.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E-DPDCH-Info-r8 */
typedef struct E_DPDCH_Info_r8 {
	E_TFCI_TableIndex_t	 e_TFCI_TableIndex;
	E_DCH_MinimumSet_E_TFCI_t	*e_DCH_MinimumSet_E_TFCI	/* OPTIONAL */;
	E_DPDCH_Reference_E_TFCIList_r7_t	 reference_E_TFCIs;
	MinReduced_E_DPDCH_GainFactor_t	*minReduced_E_DPDCH_GainFactor	/* OPTIONAL */;
	E_DPDCH_MaxChannelisationCodes_t	 maxChannelisationCodes;
	E_DPDCH_PL_NonMax_t	 pl_NonMax;
	E_DPDCH_SchedulingInfoConfiguration_t	 schedulingInfoConfiguration;
	long	*threeIndexStepThreshold	/* OPTIONAL */;
	long	*twoIndexStepThreshold	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E_DPDCH_Info_r8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E_DPDCH_Info_r8;

#ifdef __cplusplus
}
#endif

#endif	/* _E_DPDCH_Info_r8_H_ */
