/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_EnablingDelay_H_
#define	_EnablingDelay_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnablingDelay {
	EnablingDelay_radio_frames_0	= 0,
	EnablingDelay_radio_frames_1	= 1,
	EnablingDelay_radio_frames_2	= 2,
	EnablingDelay_radio_frames_4	= 3,
	EnablingDelay_radio_frames_8	= 4,
	EnablingDelay_radio_frames_16	= 5,
	EnablingDelay_radio_frames_32	= 6,
	EnablingDelay_radio_frames_64	= 7,
	EnablingDelay_radio_frames_128	= 8,
	EnablingDelay_spare7	= 9,
	EnablingDelay_spare6	= 10,
	EnablingDelay_spare5	= 11,
	EnablingDelay_spare4	= 12,
	EnablingDelay_spare3	= 13,
	EnablingDelay_spare2	= 14,
	EnablingDelay_spare1	= 15
} e_EnablingDelay;

/* EnablingDelay */
typedef long	 EnablingDelay_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnablingDelay;
asn_struct_free_f EnablingDelay_free;
asn_struct_print_f EnablingDelay_print;
asn_constr_check_f EnablingDelay_constraint;
ber_type_decoder_f EnablingDelay_decode_ber;
der_type_encoder_f EnablingDelay_encode_der;
xer_type_decoder_f EnablingDelay_decode_xer;
xer_type_encoder_f EnablingDelay_encode_xer;
per_type_decoder_f EnablingDelay_decode_uper;
per_type_encoder_f EnablingDelay_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnablingDelay_H_ */
