/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_EnvironmentCharacterisation_H_
#define	_EnvironmentCharacterisation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnvironmentCharacterisation {
	EnvironmentCharacterisation_possibleHeavyMultipathNLOS	= 0,
	EnvironmentCharacterisation_lightMultipathLOS	= 1,
	EnvironmentCharacterisation_notDefined	= 2,
	EnvironmentCharacterisation_spare	= 3
} e_EnvironmentCharacterisation;

/* EnvironmentCharacterisation */
typedef long	 EnvironmentCharacterisation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnvironmentCharacterisation;
asn_struct_free_f EnvironmentCharacterisation_free;
asn_struct_print_f EnvironmentCharacterisation_print;
asn_constr_check_f EnvironmentCharacterisation_constraint;
ber_type_decoder_f EnvironmentCharacterisation_decode_ber;
der_type_encoder_f EnvironmentCharacterisation_encode_der;
xer_type_decoder_f EnvironmentCharacterisation_decode_xer;
xer_type_encoder_f EnvironmentCharacterisation_encode_xer;
per_type_decoder_f EnvironmentCharacterisation_decode_uper;
per_type_encoder_f EnvironmentCharacterisation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnvironmentCharacterisation_H_ */
