/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_EventIDInterRAT_H_
#define	_EventIDInterRAT_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EventIDInterRAT {
	EventIDInterRAT_e3a	= 0,
	EventIDInterRAT_e3b	= 1,
	EventIDInterRAT_e3c	= 2,
	EventIDInterRAT_e3d	= 3
} e_EventIDInterRAT;

/* EventIDInterRAT */
typedef long	 EventIDInterRAT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EventIDInterRAT;
asn_struct_free_f EventIDInterRAT_free;
asn_struct_print_f EventIDInterRAT_print;
asn_constr_check_f EventIDInterRAT_constraint;
ber_type_decoder_f EventIDInterRAT_decode_ber;
der_type_encoder_f EventIDInterRAT_encode_der;
xer_type_decoder_f EventIDInterRAT_decode_xer;
xer_type_encoder_f EventIDInterRAT_encode_xer;
per_type_decoder_f EventIDInterRAT_decode_uper;
per_type_encoder_f EventIDInterRAT_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EventIDInterRAT_H_ */
