/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_Event1e_r6_H_
#define	_Event1e_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TriggeringCondition2.h"
#include "rf_phreaker/umts_rrc_asn_library/ThresholdUsedFrequency-r6.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Event1e-r6 */
typedef struct Event1e_r6 {
	TriggeringCondition2_t	 triggeringCondition;
	ThresholdUsedFrequency_r6_t	 thresholdUsedFrequency;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Event1e_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Event1e_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _Event1e_r6_H_ */
