/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_FailureCauseWithProtErrTrId_H_
#define	_FailureCauseWithProtErrTrId_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/FailureCauseWithProtErr.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* FailureCauseWithProtErrTrId */
typedef struct FailureCauseWithProtErrTrId {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	FailureCauseWithProtErr_t	 failureCause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FailureCauseWithProtErrTrId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FailureCauseWithProtErrTrId;

#ifdef __cplusplus
}
#endif

#endif	/* _FailureCauseWithProtErrTrId_H_ */
