/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_GANSSGenericData_vaxyext_H_
#define	_GANSSGenericData_vaxyext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GANSSTimeModelsList_vaxyext;
struct UE_Positioning_GANSS_ReferenceMeasurementInfo_vaxyext;
struct UE_Positioning_GANSS_Almanac_vaxyext;

/* GANSSGenericData-vaxyext */
typedef struct GANSSGenericData_vaxyext {
	struct GANSSTimeModelsList_vaxyext	*ganssTimeModelsList	/* OPTIONAL */;
	struct UE_Positioning_GANSS_ReferenceMeasurementInfo_vaxyext	*uePositioningGANSSReferenceMeasurementInfo	/* OPTIONAL */;
	struct UE_Positioning_GANSS_Almanac_vaxyext	*uePositioningGANSSAlmanac	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSGenericData_vaxyext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSGenericData_vaxyext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/GANSSTimeModelsList-vaxyext.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-ReferenceMeasurementInfo-vaxyext.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-Almanac-vaxyext.h"

#endif	/* _GANSSGenericData_vaxyext_H_ */
