/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_GANSSMeasurementParameters_H_
#define	_GANSSMeasurementParameters_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum multipathIndicator {
	multipathIndicator_nm	= 0,
	multipathIndicator_low	= 1,
	multipathIndicator_medium	= 2,
	multipathIndicator_high	= 3
} e_multipathIndicator;

/* GANSSMeasurementParameters */
typedef struct GANSSMeasurementParameters {
	A_SEQUENCE_OF(struct GANSSMeasurementParameters__Member {
		long	 satId;
		long	 cSurNzero;
		long	 multipathIndicator;
		BIT_STRING_t	*carrierQualityIndication	/* OPTIONAL */;
		long	 ganssCodePhase;
		long	*ganssIntegerCodePhase	/* OPTIONAL */;
		long	 codePhaseRmsError;
		long	 doppler;
		long	*adr	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSMeasurementParameters_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_multipathIndicator_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GANSSMeasurementParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSMeasurementParameters_H_ */
