/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#include <rf_phreaker/umts_rrc_asn_library/asn_internal.h>

#include "rf_phreaker/umts_rrc_asn_library/GANSSGenericData-vaxyext.h"

static asn_TYPE_member_t asn_MBR_GANSSGenericData_vaxyext_1[] = {
	{ ATF_POINTER, 3, offsetof(struct GANSSGenericData_vaxyext, ganssTimeModelsList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSTimeModelsList_vaxyext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssTimeModelsList"
		},
	{ ATF_POINTER, 2, offsetof(struct GANSSGenericData_vaxyext, uePositioningGANSSReferenceMeasurementInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_GANSS_ReferenceMeasurementInfo_vaxyext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uePositioningGANSSReferenceMeasurementInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct GANSSGenericData_vaxyext, uePositioningGANSSAlmanac),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_Positioning_GANSS_Almanac_vaxyext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"uePositioningGANSSAlmanac"
		},
};
static int asn_MAP_GANSSGenericData_vaxyext_oms_1[] = { 0, 1, 2 };
static ber_tlv_tag_t asn_DEF_GANSSGenericData_vaxyext_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_GANSSGenericData_vaxyext_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssTimeModelsList at 23643 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uePositioningGANSSReferenceMeasurementInfo at 23646 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* uePositioningGANSSAlmanac at 23647 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GANSSGenericData_vaxyext_specs_1 = {
	sizeof(struct GANSSGenericData_vaxyext),
	offsetof(struct GANSSGenericData_vaxyext, _asn_ctx),
	asn_MAP_GANSSGenericData_vaxyext_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GANSSGenericData_vaxyext_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GANSSGenericData_vaxyext = {
	"GANSSGenericData-vaxyext",
	"GANSSGenericData-vaxyext",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GANSSGenericData_vaxyext_tags_1,
	sizeof(asn_DEF_GANSSGenericData_vaxyext_tags_1)
		/sizeof(asn_DEF_GANSSGenericData_vaxyext_tags_1[0]), /* 1 */
	asn_DEF_GANSSGenericData_vaxyext_tags_1,	/* Same as above */
	sizeof(asn_DEF_GANSSGenericData_vaxyext_tags_1)
		/sizeof(asn_DEF_GANSSGenericData_vaxyext_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GANSSGenericData_vaxyext_1,
	3,	/* Elements count */
	&asn_SPC_GANSSGenericData_vaxyext_specs_1	/* Additional specs */
};

