/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_GANSSSatelliteInformation_H_
#define	_GANSSSatelliteInformation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExtraDoppler;
struct AzimuthAndElevation;

/* GANSSSatelliteInformation */
typedef struct GANSSSatelliteInformation {
	long	 ganssSatId;
	long	 dopplerZeroOrder;
	struct ExtraDoppler	*extraDoppler	/* OPTIONAL */;
	long	 codePhase;
	long	 integerCodePhase;
	BIT_STRING_t	 codePhaseSearchWindow;
	struct AzimuthAndElevation	*azimuthandElevation	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSSatelliteInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSSatelliteInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/ExtraDoppler.h"
#include "rf_phreaker/umts_rrc_asn_library/AzimuthAndElevation.h"

#endif	/* _GANSSSatelliteInformation_H_ */
