/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_GsmSecurityCapability_H_
#define	_GsmSecurityCapability_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GsmSecurityCapability {
	GsmSecurityCapability_a5_7	= 0,
	GsmSecurityCapability_a5_6	= 1,
	GsmSecurityCapability_a5_5	= 2,
	GsmSecurityCapability_a5_4	= 3,
	GsmSecurityCapability_a5_3	= 4,
	GsmSecurityCapability_a5_2	= 5,
	GsmSecurityCapability_a5_1	= 6
} e_GsmSecurityCapability;

/* GsmSecurityCapability */
typedef BIT_STRING_t	 GsmSecurityCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GsmSecurityCapability;
asn_struct_free_f GsmSecurityCapability_free;
asn_struct_print_f GsmSecurityCapability_print;
asn_constr_check_f GsmSecurityCapability_constraint;
ber_type_decoder_f GsmSecurityCapability_decode_ber;
der_type_encoder_f GsmSecurityCapability_encode_der;
xer_type_decoder_f GsmSecurityCapability_decode_xer;
xer_type_encoder_f GsmSecurityCapability_encode_xer;
per_type_decoder_f GsmSecurityCapability_decode_uper;
per_type_encoder_f GsmSecurityCapability_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GsmSecurityCapability_H_ */
