/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HandoverFromUTRANCommand_EUTRA_H_
#define	_HandoverFromUTRANCommand_EUTRA_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/HandoverFromUTRANCommand-EUTRA-r8-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR {
	HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR_NOTHING,	/* No components present */
	HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR_r8,
	HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR_criticalExtensions
} HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR;

/* HandoverFromUTRANCommand-EUTRA */
typedef struct HandoverFromUTRANCommand_EUTRA {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	struct HandoverFromUTRANCommand_EUTRA__criticalExtensions {
		HandoverFromUTRANCommand_EUTRA__criticalExtensions_PR present;
		union HandoverFromUTRANCommand_EUTRA__criticalExtensions_u {
			struct HandoverFromUTRANCommand_EUTRA__criticalExtensions__r8 {
				HandoverFromUTRANCommand_EUTRA_r8_IEs_t	 handoverFromUTRANCommand_EUTRA_r8;
				BIT_STRING_t	*handoverFromUTRANCommand_EUTRA_r8_add_ext	/* OPTIONAL */;
				struct HandoverFromUTRANCommand_EUTRA__criticalExtensions__r8__nonCriticalExtensions {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} r8;
			struct HandoverFromUTRANCommand_EUTRA__criticalExtensions__criticalExtensions {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverFromUTRANCommand_EUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverFromUTRANCommand_EUTRA;

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverFromUTRANCommand_EUTRA_H_ */
