/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HARQ_Info_H_
#define	_HARQ_Info_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/HARQMemorySize.h"
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HARQ_Info__memoryPartitioning_PR {
	HARQ_Info__memoryPartitioning_PR_NOTHING,	/* No components present */
	HARQ_Info__memoryPartitioning_PR_implicit,
	HARQ_Info__memoryPartitioning_PR_explicit
} HARQ_Info__memoryPartitioning_PR;

/* HARQ-Info */
typedef struct HARQ_Info {
	long	 numberOfProcesses;
	struct HARQ_Info__memoryPartitioning {
		HARQ_Info__memoryPartitioning_PR present;
		union HARQ_Info__memoryPartitioning_u {
			NULL_t	 implicit;
			struct HARQ_Info__memoryPartitioning__explicit {
				A_SEQUENCE_OF(HARQMemorySize_t) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} explicit_; // Changed so we can compile on microsoft.
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} memoryPartitioning;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HARQ_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HARQ_Info;

#ifdef __cplusplus
}
#endif

#endif	/* _HARQ_Info_H_ */
