/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HorizontalWithVerticalVelocityAndUncertainty_H_
#define	_HorizontalWithVerticalVelocityAndUncertainty_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HorizontalWithVerticalVelocityAndUncertainty__verticalSpeedDirection {
	HorizontalWithVerticalVelocityAndUncertainty__verticalSpeedDirection_upward	= 0,
	HorizontalWithVerticalVelocityAndUncertainty__verticalSpeedDirection_downward	= 1
} e_HorizontalWithVerticalVelocityAndUncertainty__verticalSpeedDirection;

/* HorizontalWithVerticalVelocityAndUncertainty */
typedef struct HorizontalWithVerticalVelocityAndUncertainty {
	long	 verticalSpeedDirection;
	long	 bearing;
	long	 horizontalSpeed;
	long	 verticalSpeed;
	long	 horizontalUncertaintySpeed;
	long	 verticalUncertaintySpeed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HorizontalWithVerticalVelocityAndUncertainty_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_verticalSpeedDirection_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_HorizontalWithVerticalVelocityAndUncertainty;

#ifdef __cplusplus
}
#endif

#endif	/* _HorizontalWithVerticalVelocityAndUncertainty_H_ */
