/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HS_SCCH_TDD768_H_
#define	_HS_SCCH_TDD768_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber.h"
#include "rf_phreaker/umts_rrc_asn_library/DL-TS-ChannelisationCode-VHCR.h"
#include "rf_phreaker/umts_rrc_asn_library/MidambleConfigurationBurstType1and3.h"
#include "rf_phreaker/umts_rrc_asn_library/HS-SICH-Configuration-TDD768.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftLong.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HS_SCCH_TDD768__midambleAllocationMode_PR {
	HS_SCCH_TDD768__midambleAllocationMode_PR_NOTHING,	/* No components present */
	HS_SCCH_TDD768__midambleAllocationMode_PR_defaultMidamble,
	HS_SCCH_TDD768__midambleAllocationMode_PR_commonMidamble,
	HS_SCCH_TDD768__midambleAllocationMode_PR_ueSpecificMidamble
} HS_SCCH_TDD768__midambleAllocationMode_PR;

/* HS-SCCH-TDD768 */
typedef struct HS_SCCH_TDD768 {
	TimeslotNumber_t	 timeslotNumber;
	DL_TS_ChannelisationCode_VHCR_t	 channelisationCode;
	struct HS_SCCH_TDD768__midambleAllocationMode {
		HS_SCCH_TDD768__midambleAllocationMode_PR present;
		union HS_SCCH_TDD768__midambleAllocationMode_u {
			NULL_t	 defaultMidamble;
			NULL_t	 commonMidamble;
			struct HS_SCCH_TDD768__midambleAllocationMode__ueSpecificMidamble {
				MidambleShiftLong_t	 midambleShift;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ueSpecificMidamble;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} midambleAllocationMode;
	MidambleConfigurationBurstType1and3_t	 midambleconfiguration;
	HS_SICH_Configuration_TDD768_t	 hs_sich_configuration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HS_SCCH_TDD768_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_SCCH_TDD768;

#ifdef __cplusplus
}
#endif

#endif	/* _HS_SCCH_TDD768_H_ */
