/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HS_SICH_Configuration_TDD128_r6_H_
#define	_HS_SICH_Configuration_TDD128_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber-LCR-r4.h"
#include "rf_phreaker/umts_rrc_asn_library/HS-ChannelisationCode-LCR.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftLong.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR {
	HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR_NOTHING,	/* No components present */
	HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR_defaultMidamble,
	HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR_ueSpecificMidamble
} HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR;

/* HS-SICH-Configuration-TDD128-r6 */
typedef struct HS_SICH_Configuration_TDD128_r6 {
	TimeslotNumber_LCR_r4_t	 timeslotNumber;
	HS_ChannelisationCode_LCR_t	 channelisationCode;
	struct HS_SICH_Configuration_TDD128_r6__midambleAllocationMode {
		HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_PR present;
		union HS_SICH_Configuration_TDD128_r6__midambleAllocationMode_u {
			NULL_t	 defaultMidamble;
			struct HS_SICH_Configuration_TDD128_r6__midambleAllocationMode__ueSpecificMidamble {
				MidambleShiftLong_t	 midambleShift;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} ueSpecificMidamble;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} midambleAllocationMode;
	long	 midambleConfiguration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HS_SICH_Configuration_TDD128_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_SICH_Configuration_TDD128_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _HS_SICH_Configuration_TDD128_r6_H_ */
