/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HS_SICH_ReferenceSignalInfoList_H_
#define	_HS_SICH_ReferenceSignalInfoList_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HS-SICH-ReferenceSignalInfoList */
typedef struct HS_SICH_ReferenceSignalInfoList {
	A_SEQUENCE_OF(struct HS_SICH_ReferenceSignalInfoList__Member {
		long	 midambleConfiguration;
		long	 midambleShift;
		long	 timeSlot;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HS_SICH_ReferenceSignalInfoList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_SICH_ReferenceSignalInfoList;

#ifdef __cplusplus
}
#endif

#endif	/* _HS_SICH_ReferenceSignalInfoList_H_ */
