/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_HS_SCCH_TDD128_MultiCarrier_H_
#define	_HS_SCCH_TDD128_MultiCarrier_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UARFCN.h"
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber-LCR-r4.h"
#include "rf_phreaker/umts_rrc_asn_library/HS-ChannelisationCode-LCR.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/umts_rrc_asn_library/Bler-Target.h"
#include "rf_phreaker/umts_rrc_asn_library/HS-SICH-Configuration-TDD128.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR {
	HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR_NOTHING,	/* No components present */
	HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR_defaultMidamble,
	HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR_commonMidamble,
	HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR_ueSpecificMidamble
} HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR;

/* HS-SCCH-TDD128-MultiCarrier */
typedef struct HS_SCCH_TDD128_MultiCarrier {
	UARFCN_t	 uarfcn_HS_SCCH_Rx;
	TimeslotNumber_LCR_r4_t	 timeslotNumber;
	HS_ChannelisationCode_LCR_t	 firstChannelisationCode;
	HS_ChannelisationCode_LCR_t	 secondChannelisationCode;
	struct HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode {
		HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_PR present;
		union HS_SCCH_TDD128_MultiCarrier__midambleAllocationMode_u {
			NULL_t	 defaultMidamble;
			NULL_t	 commonMidamble;
			long	 ueSpecificMidamble;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} midambleAllocationMode;
	long	 midambleConfiguration;
	Bler_Target_t	 bler_target;
	HS_SICH_Configuration_TDD128_t	 hs_sich_configuration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HS_SCCH_TDD128_MultiCarrier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HS_SCCH_TDD128_MultiCarrier;

#ifdef __cplusplus
}
#endif

#endif	/* _HS_SCCH_TDD128_MultiCarrier_H_ */
