/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_IndividualTimeslotInfo_LCR_r4_ext_H_
#define	_IndividualTimeslotInfo_LCR_r4_ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftAndBurstType-LCR-r4.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IndividualTimeslotInfo_LCR_r4_ext__modulation {
	IndividualTimeslotInfo_LCR_r4_ext__modulation_mod_QPSK	= 0,
	IndividualTimeslotInfo_LCR_r4_ext__modulation_mod_8PSK	= 1
} e_IndividualTimeslotInfo_LCR_r4_ext__modulation;
typedef enum IndividualTimeslotInfo_LCR_r4_ext__ss_TPC_Symbols {
	IndividualTimeslotInfo_LCR_r4_ext__ss_TPC_Symbols_zero	= 0,
	IndividualTimeslotInfo_LCR_r4_ext__ss_TPC_Symbols_one	= 1,
	IndividualTimeslotInfo_LCR_r4_ext__ss_TPC_Symbols_sixteenOverSF	= 2
} e_IndividualTimeslotInfo_LCR_r4_ext__ss_TPC_Symbols;

/* IndividualTimeslotInfo-LCR-r4-ext */
typedef struct IndividualTimeslotInfo_LCR_r4_ext {
	MidambleShiftAndBurstType_LCR_r4_t	 midambleShiftAndBurstType;
	long	 modulation;
	long	 ss_TPC_Symbols;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualTimeslotInfo_LCR_r4_ext_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_modulation_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ss_TPC_Symbols_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_IndividualTimeslotInfo_LCR_r4_ext;

#ifdef __cplusplus
}
#endif

#endif	/* _IndividualTimeslotInfo_LCR_r4_ext_H_ */
