/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_IndividualTS_Interference_H_
#define	_IndividualTS_Interference_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber.h"
#include "rf_phreaker/umts_rrc_asn_library/TDD-UL-Interference.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IndividualTS-Interference */
typedef struct IndividualTS_Interference {
	TimeslotNumber_t	 timeslot;
	TDD_UL_Interference_t	 ul_TimeslotInterference;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IndividualTS_Interference_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IndividualTS_Interference;

#ifdef __cplusplus
}
#endif

#endif	/* _IndividualTS_Interference_H_ */
