/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_IntegrityProtectionModeInfo_r7_H_
#define	_IntegrityProtectionModeInfo_r7_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/IntegrityProtectionModeCommand.h"
#include "rf_phreaker/umts_rrc_asn_library/IntegrityProtectionAlgorithm-r7.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntegrityProtectionModeInfo-r7 */
typedef struct IntegrityProtectionModeInfo_r7 {
	IntegrityProtectionModeCommand_t	 integrityProtectionModeCommand;
	IntegrityProtectionAlgorithm_r7_t	*integrityProtectionAlgorithm	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntegrityProtectionModeInfo_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntegrityProtectionModeInfo_r7;

#ifdef __cplusplus
}
#endif

#endif	/* _IntegrityProtectionModeInfo_r7_H_ */
