/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_InterRAT_HO_FailureCause_H_
#define	_InterRAT_HO_FailureCause_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/ProtocolErrorInformation.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InterRAT_HO_FailureCause_PR {
	InterRAT_HO_FailureCause_PR_NOTHING,	/* No components present */
	InterRAT_HO_FailureCause_PR_configurationUnacceptable,
	InterRAT_HO_FailureCause_PR_physicalChannelFailure,
	InterRAT_HO_FailureCause_PR_protocolError,
	InterRAT_HO_FailureCause_PR_interRAT_ProtocolError,
	InterRAT_HO_FailureCause_PR_unspecified,
	InterRAT_HO_FailureCause_PR_spare11,
	InterRAT_HO_FailureCause_PR_spare10,
	InterRAT_HO_FailureCause_PR_spare9,
	InterRAT_HO_FailureCause_PR_spare8,
	InterRAT_HO_FailureCause_PR_spare7,
	InterRAT_HO_FailureCause_PR_spare6,
	InterRAT_HO_FailureCause_PR_spare5,
	InterRAT_HO_FailureCause_PR_spare4,
	InterRAT_HO_FailureCause_PR_spare3,
	InterRAT_HO_FailureCause_PR_spare2,
	InterRAT_HO_FailureCause_PR_spare1
} InterRAT_HO_FailureCause_PR;

/* InterRAT-HO-FailureCause */
typedef struct InterRAT_HO_FailureCause {
	InterRAT_HO_FailureCause_PR present;
	union InterRAT_HO_FailureCause_u {
		NULL_t	 configurationUnacceptable;
		NULL_t	 physicalChannelFailure;
		ProtocolErrorInformation_t	 protocolError;
		NULL_t	 interRAT_ProtocolError;
		NULL_t	 unspecified;
		NULL_t	 spare11;
		NULL_t	 spare10;
		NULL_t	 spare9;
		NULL_t	 spare8;
		NULL_t	 spare7;
		NULL_t	 spare6;
		NULL_t	 spare5;
		NULL_t	 spare4;
		NULL_t	 spare3;
		NULL_t	 spare2;
		NULL_t	 spare1;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRAT_HO_FailureCause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRAT_HO_FailureCause;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRAT_HO_FailureCause_H_ */
