/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_InterFreqCellInfoList_r9_H_
#define	_InterFreqCellInfoList_r9_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RemovedInterFreqCellList;
struct NewInterFreqCellList_r9;
struct CellsForInterFreqMeasList;
struct CSGInterFreqCellInfoList;
struct InterFreqSIAcquisition;

/* InterFreqCellInfoList-r9 */
typedef struct InterFreqCellInfoList_r9 {
	struct RemovedInterFreqCellList	*removedInterFreqCellList	/* OPTIONAL */;
	struct NewInterFreqCellList_r9	*newInterFreqCellList	/* OPTIONAL */;
	struct CellsForInterFreqMeasList	*cellsForInterFreqMeasList	/* OPTIONAL */;
	struct CSGInterFreqCellInfoList	*cSGInterFreqCellInfoList	/* OPTIONAL */;
	struct InterFreqSIAcquisition	*interFreqSIAcquisition	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFreqCellInfoList_r9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFreqCellInfoList_r9;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/RemovedInterFreqCellList.h"
#include "rf_phreaker/umts_rrc_asn_library/NewInterFreqCellList-r9.h"
#include "rf_phreaker/umts_rrc_asn_library/CellsForInterFreqMeasList.h"
#include "rf_phreaker/umts_rrc_asn_library/CSGInterFreqCellInfoList.h"
#include "rf_phreaker/umts_rrc_asn_library/InterFreqSIAcquisition.h"

#endif	/* _InterFreqCellInfoList_r9_H_ */
