/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_InterRATCellInfoList_B_H_
#define	_InterRATCellInfoList_B_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RemovedInterRATCellList.h"
#include "rf_phreaker/umts_rrc_asn_library/NewInterRATCellList-B.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InterRATCellInfoList-B */
typedef struct InterRATCellInfoList_B {
	RemovedInterRATCellList_t	 removedInterRATCellList;
	NewInterRATCellList_B_t	 newInterRATCellList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterRATCellInfoList_B_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterRATCellInfoList_B;

#ifdef __cplusplus
}
#endif

#endif	/* _InterRATCellInfoList_B_H_ */
