/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_InterFrequencyMeasurement_r10_H_
#define	_InterFrequencyMeasurement_r10_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/InterFreqCellInfoList-r10.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/umts_rrc_asn_library/InterFreqReportCriteria-r10.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InterFreqMeasQuantity;
struct InterFreqReportingQuantity;
struct MeasurementValidity;
struct UE_AutonomousUpdateMode;
struct FreqIndexListForEnhancedMeas;

/* InterFrequencyMeasurement-r10 */
typedef struct InterFrequencyMeasurement_r10 {
	InterFreqCellInfoList_r10_t	 interFreqCellInfoList;
	struct InterFreqMeasQuantity	*interFreqMeasQuantity	/* OPTIONAL */;
	struct InterFreqReportingQuantity	*interFreqReportingQuantity	/* OPTIONAL */;
	struct MeasurementValidity	*measurementValidity	/* OPTIONAL */;
	struct UE_AutonomousUpdateMode	*interFreqSetUpdate	/* OPTIONAL */;
	long	*adjacentFrequencyIndex	/* OPTIONAL */;
	long	*interBandFrequencyIndex	/* OPTIONAL */;
	struct FreqIndexListForEnhancedMeas	*freqIndexListForEnhancedMeas	/* OPTIONAL */;
	InterFreqReportCriteria_r10_t	 reportCriteria;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InterFrequencyMeasurement_r10_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InterFrequencyMeasurement_r10;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/InterFreqMeasQuantity.h"
#include "rf_phreaker/umts_rrc_asn_library/InterFreqReportingQuantity.h"
#include "rf_phreaker/umts_rrc_asn_library/MeasurementValidity.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-AutonomousUpdateMode.h"
#include "rf_phreaker/umts_rrc_asn_library/FreqIndexListForEnhancedMeas.h"

#endif	/* _InterFrequencyMeasurement_r10_H_ */
