/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_IntegrityProtectionModeCommand_H_
#define	_IntegrityProtectionModeCommand_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/IntegrityProtInitNumber.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/IntegrityProtActivationInfo.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntegrityProtectionModeCommand_PR {
	IntegrityProtectionModeCommand_PR_NOTHING,	/* No components present */
	IntegrityProtectionModeCommand_PR_startIntegrityProtection,
	IntegrityProtectionModeCommand_PR_modify
} IntegrityProtectionModeCommand_PR;

/* IntegrityProtectionModeCommand */
typedef struct IntegrityProtectionModeCommand {
	IntegrityProtectionModeCommand_PR present;
	union IntegrityProtectionModeCommand_u {
		struct IntegrityProtectionModeCommand__startIntegrityProtection {
			IntegrityProtInitNumber_t	 integrityProtInitNumber;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} startIntegrityProtection;
		struct IntegrityProtectionModeCommand__modify {
			IntegrityProtActivationInfo_t	 dl_IntegrityProtActivationInfo;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} modify;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntegrityProtectionModeCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntegrityProtectionModeCommand;

#ifdef __cplusplus
}
#endif

#endif	/* _IntegrityProtectionModeCommand_H_ */
