/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_IP_Length_H_
#define	_IP_Length_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IP_Length {
	IP_Length_ipl5	= 0,
	IP_Length_ipl10	= 1
} e_IP_Length;

/* IP-Length */
typedef long	 IP_Length_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IP_Length;
asn_struct_free_f IP_Length_free;
asn_struct_print_f IP_Length_print;
asn_constr_check_f IP_Length_constraint;
ber_type_decoder_f IP_Length_decode_ber;
der_type_encoder_f IP_Length_encode_der;
xer_type_decoder_f IP_Length_decode_xer;
xer_type_encoder_f IP_Length_encode_xer;
per_type_decoder_f IP_Length_decode_uper;
per_type_encoder_f IP_Length_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IP_Length_H_ */
