/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_LoggedMeasIntrafreqNeighbourMeas_TDD128_H_
#define	_LoggedMeasIntrafreqNeighbourMeas_TDD128_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/CellParametersID.h"
#include "rf_phreaker/umts_rrc_asn_library/PrimaryCCPCH-RSCP.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LoggedMeasIntrafreqNeighbourMeas-TDD128 */
typedef struct LoggedMeasIntrafreqNeighbourMeas_TDD128 {
	CellParametersID_t	 cellParametersID;
	PrimaryCCPCH_RSCP_t	 primaryCCPCH_RSCP;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LoggedMeasIntrafreqNeighbourMeas_TDD128_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LoggedMeasIntrafreqNeighbourMeas_TDD128;

#ifdef __cplusplus
}
#endif

#endif	/* _LoggedMeasIntrafreqNeighbourMeas_TDD128_H_ */
