/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MaxTransportBlocksUL_H_
#define	_MaxTransportBlocksUL_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MaxTransportBlocksUL {
	MaxTransportBlocksUL_dummy	= 0,
	MaxTransportBlocksUL_tb4	= 1,
	MaxTransportBlocksUL_tb8	= 2,
	MaxTransportBlocksUL_tb16	= 3,
	MaxTransportBlocksUL_tb32	= 4,
	MaxTransportBlocksUL_tb48	= 5,
	MaxTransportBlocksUL_tb64	= 6,
	MaxTransportBlocksUL_tb96	= 7,
	MaxTransportBlocksUL_tb128	= 8,
	MaxTransportBlocksUL_tb256	= 9,
	MaxTransportBlocksUL_tb512	= 10
} e_MaxTransportBlocksUL;

/* MaxTransportBlocksUL */
typedef long	 MaxTransportBlocksUL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MaxTransportBlocksUL;
asn_struct_free_f MaxTransportBlocksUL_free;
asn_struct_print_f MaxTransportBlocksUL_print;
asn_constr_check_f MaxTransportBlocksUL_constraint;
ber_type_decoder_f MaxTransportBlocksUL_decode_ber;
der_type_encoder_f MaxTransportBlocksUL_encode_der;
xer_type_decoder_f MaxTransportBlocksUL_decode_xer;
xer_type_encoder_f MaxTransportBlocksUL_encode_xer;
per_type_decoder_f MaxTransportBlocksUL_decode_uper;
per_type_encoder_f MaxTransportBlocksUL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MaxTransportBlocksUL_H_ */
