/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MBMSModificationRequest_v6f0ext_IEs_H_
#define	_MBMSModificationRequest_v6f0ext_IEs_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMSModificationRequest_v6f0ext_IEs__mbmsSupportOfServiceChangeForAPtpRB {
	MBMSModificationRequest_v6f0ext_IEs__mbmsSupportOfServiceChangeForAPtpRB_true	= 0
} e_MBMSModificationRequest_v6f0ext_IEs__mbmsSupportOfServiceChangeForAPtpRB;

/* MBMSModificationRequest-v6f0ext-IEs */
typedef struct MBMSModificationRequest_v6f0ext_IEs {
	long	*mbmsSupportOfServiceChangeForAPtpRB	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMSModificationRequest_v6f0ext_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mbmsSupportOfServiceChangeForAPtpRB_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBMSModificationRequest_v6f0ext_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMSModificationRequest_v6f0ext_IEs_H_ */
