/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MBMS_TransmissionIdentity_H_
#define	_MBMS_TransmissionIdentity_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MBMS-ServiceIdentity-r6.h"
#include "rf_phreaker/umts_rrc_asn_library/MBMS-SessionIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MBMS-TransmissionIdentity */
typedef struct MBMS_TransmissionIdentity {
	MBMS_ServiceIdentity_r6_t	 mbms_ServiceIdentity;
	MBMS_SessionIdentity_t	*mbms_SessionIdentity	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_TransmissionIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_TransmissionIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_TransmissionIdentity_H_ */
