/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MBMS_ModifedService_r6_H_
#define	_MBMS_ModifedService_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MBMS-TransmissionIdentity.h"
#include "rf_phreaker/umts_rrc_asn_library/MBMS-RequiredUEAction-Mod.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/BOOLEAN.h>
#include "rf_phreaker/umts_rrc_asn_library/MBMS-PFLIndex.h"
#include "rf_phreaker/umts_rrc_asn_library/MBMS-PFLInfo.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMS_ModifedService_r6__mbms_PreferredFrequency_PR {
	MBMS_ModifedService_r6__mbms_PreferredFrequency_PR_NOTHING,	/* No components present */
	MBMS_ModifedService_r6__mbms_PreferredFrequency_PR_mcch,
	MBMS_ModifedService_r6__mbms_PreferredFrequency_PR_dcch
} MBMS_ModifedService_r6__mbms_PreferredFrequency_PR;
typedef enum MBMS_ModifedService_r6__dummy {
	MBMS_ModifedService_r6__dummy_true	= 0
} e_MBMS_ModifedService_r6__dummy;

/* MBMS-ModifedService-r6 */
typedef struct MBMS_ModifedService_r6 {
	MBMS_TransmissionIdentity_t	 mbms_TransmissionIdentity;
	MBMS_RequiredUEAction_Mod_t	 mbms_RequiredUEAction;
	struct MBMS_ModifedService_r6__mbms_PreferredFrequency {
		MBMS_ModifedService_r6__mbms_PreferredFrequency_PR present;
		union MBMS_ModifedService_r6__mbms_PreferredFrequency_u {
			MBMS_PFLIndex_t	 mcch;
			MBMS_PFLInfo_t	 dcch;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *mbms_PreferredFrequency;
	long	*dummy	/* OPTIONAL */;
	BOOLEAN_t	 continueMCCHReading;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_ModifedService_r6_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dummy_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_ModifedService_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_ModifedService_r6_H_ */
