/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MBMS_ModifiedServiceList_LCR_v7c0ext_H_
#define	_MBMS_ModifiedServiceList_LCR_v7c0ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBMS_ModifiedService_LCR_v7c0ext;

/* MBMS-ModifiedServiceList-LCR-v7c0ext */
typedef struct MBMS_ModifiedServiceList_LCR_v7c0ext {
	A_SEQUENCE_OF(struct MBMS_ModifiedService_LCR_v7c0ext) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_ModifiedServiceList_LCR_v7c0ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_ModifiedServiceList_LCR_v7c0ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/MBMS-ModifiedService-LCR-v7c0ext.h"

#endif	/* _MBMS_ModifiedServiceList_LCR_v7c0ext_H_ */
