/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MBSFNOnlyService_H_
#define	_MBSFNOnlyService_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBSFNOnlyService {
	MBSFNOnlyService_true	= 0
} e_MBSFNOnlyService;

/* MBSFNOnlyService */
typedef long	 MBSFNOnlyService_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSFNOnlyService;
asn_struct_free_f MBSFNOnlyService_free;
asn_struct_print_f MBSFNOnlyService_print;
asn_constr_check_f MBSFNOnlyService_constraint;
ber_type_decoder_f MBSFNOnlyService_decode_ber;
der_type_encoder_f MBSFNOnlyService_encode_der;
xer_type_decoder_f MBSFNOnlyService_decode_xer;
xer_type_encoder_f MBSFNOnlyService_encode_xer;
per_type_decoder_f MBSFNOnlyService_decode_uper;
per_type_encoder_f MBSFNOnlyService_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MBSFNOnlyService_H_ */
