/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementOccasionPatternParameter_H_
#define	_MeasurementOccasionPatternParameter_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementOccasionPatternParameter */
typedef struct MeasurementOccasionPatternParameter {
	long	 measurement_Occasion_Coeff;
	long	 measurement_Occasion_Offset;
	long	 measurement_Occasion_Length;
	BIT_STRING_t	*timeslotBitmap	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementOccasionPatternParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementOccasionPatternParameter;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementOccasionPatternParameter_H_ */
