/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementControlFailure_H_
#define	_MeasurementControlFailure_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/FailureCauseWithProtErr.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/MeasurementControlFailure-v590ext-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementControlFailure */
typedef struct MeasurementControlFailure {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	FailureCauseWithProtErr_t	 failureCause;
	struct MeasurementControlFailure__laterNonCriticalExtensions {
		BIT_STRING_t	*measurementControlFailure_r3_add_ext	/* OPTIONAL */;
		struct MeasurementControlFailure__laterNonCriticalExtensions__v590NonCriticalExtensions {
			MeasurementControlFailure_v590ext_IEs_t	 measurementControlFailure_v590ext;
			struct MeasurementControlFailure__laterNonCriticalExtensions__v590NonCriticalExtensions__nonCriticalExtensions {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *v590NonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laterNonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementControlFailure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementControlFailure;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementControlFailure_H_ */
