/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementCommand_r7_H_
#define	_MeasurementCommand_r7_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MeasurementType-r7.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementCommand_r7_PR {
	MeasurementCommand_r7_PR_NOTHING,	/* No components present */
	MeasurementCommand_r7_PR_setup,
	MeasurementCommand_r7_PR_modify,
	MeasurementCommand_r7_PR_release
} MeasurementCommand_r7_PR;

/* Forward declarations */
struct MeasurementType_r7;

/* MeasurementCommand-r7 */
typedef struct MeasurementCommand_r7 {
	MeasurementCommand_r7_PR present;
	union MeasurementCommand_r7_u {
		MeasurementType_r7_t	 setup;
		struct MeasurementCommand_r7__modify {
			struct MeasurementType_r7	*measurementType	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} modify;
		NULL_t	 release;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCommand_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCommand_r7;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/MeasurementType-r7.h"

#endif	/* _MeasurementCommand_r7_H_ */
