/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementReportingMode_H_
#define	_MeasurementReportingMode_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TransferMode.h"
#include "rf_phreaker/umts_rrc_asn_library/PeriodicalOrEventTrigger.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementReportingMode */
typedef struct MeasurementReportingMode {
	TransferMode_t	 measurementReportTransferMode;
	PeriodicalOrEventTrigger_t	 periodicalOrEventTrigger;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementReportingMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementReportingMode;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementReportingMode_H_ */
