/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Internode-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MeasurementCapability_r4_H_
#define	_MeasurementCapability_r4_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/CompressedModeMeasCapability-r4.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementCapability-r4 */
typedef struct MeasurementCapability_r4 {
	CompressedModeMeasCapability_r4_t	 downlinkCompressedMode;
	CompressedModeMeasCapability_r4_t	 uplinkCompressedMode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementCapability_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementCapability_r4;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementCapability_r4_H_ */
