/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_MidambleShiftLong_H_
#define	_MidambleShiftLong_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MidambleShiftLong */
typedef long	 MidambleShiftLong_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MidambleShiftLong;
asn_struct_free_f MidambleShiftLong_free;
asn_struct_print_f MidambleShiftLong_print;
asn_constr_check_f MidambleShiftLong_constraint;
ber_type_decoder_f MidambleShiftLong_decode_ber;
der_type_encoder_f MidambleShiftLong_encode_der;
xer_type_decoder_f MidambleShiftLong_decode_xer;
xer_type_encoder_f MidambleShiftLong_encode_xer;
per_type_decoder_f MidambleShiftLong_decode_uper;
per_type_encoder_f MidambleShiftLong_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _MidambleShiftLong_H_ */
