/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_N_GAP_H_
#define	_N_GAP_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum N_GAP {
	N_GAP_f2	= 0,
	N_GAP_f4	= 1,
	N_GAP_f8	= 2
} e_N_GAP;

/* N-GAP */
typedef long	 N_GAP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_N_GAP;
asn_struct_free_f N_GAP_free;
asn_struct_print_f N_GAP_print;
asn_constr_check_f N_GAP_constraint;
ber_type_decoder_f N_GAP_decode_ber;
der_type_encoder_f N_GAP_encode_der;
xer_type_decoder_f N_GAP_decode_xer;
xer_type_encoder_f N_GAP_encode_xer;
per_type_decoder_f N_GAP_decode_uper;
per_type_encoder_f N_GAP_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _N_GAP_H_ */
