/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_NAS_SystemInformationANSI_41_H_
#define	_NAS_SystemInformationANSI_41_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/ANSI-41-NAS-Parameter.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NAS-SystemInformationANSI-41 */
typedef ANSI_41_NAS_Parameter_t	 NAS_SystemInformationANSI_41_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NAS_SystemInformationANSI_41;
asn_struct_free_f NAS_SystemInformationANSI_41_free;
asn_struct_print_f NAS_SystemInformationANSI_41_print;
asn_constr_check_f NAS_SystemInformationANSI_41_constraint;
ber_type_decoder_f NAS_SystemInformationANSI_41_decode_ber;
der_type_encoder_f NAS_SystemInformationANSI_41_encode_der;
xer_type_decoder_f NAS_SystemInformationANSI_41_decode_xer;
xer_type_encoder_f NAS_SystemInformationANSI_41_encode_xer;
per_type_decoder_f NAS_SystemInformationANSI_41_decode_uper;
per_type_encoder_f NAS_SystemInformationANSI_41_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _NAS_SystemInformationANSI_41_H_ */
