/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_Neighbour_H_
#define	_Neighbour_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/NeighbourQuality.h"
#include "rf_phreaker/umts_rrc_asn_library/SFN-SFN-ObsTimeDifference2.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Neighbour__modeSpecificInfo_PR {
	Neighbour__modeSpecificInfo_PR_NOTHING,	/* No components present */
	Neighbour__modeSpecificInfo_PR_fdd,
	Neighbour__modeSpecificInfo_PR_tdd
} Neighbour__modeSpecificInfo_PR;

/* Forward declarations */
struct PrimaryCPICH_Info;
struct UE_RX_TX_TimeDifferenceType2Info;
struct CellAndChannelIdentity;

/* Neighbour */
typedef struct Neighbour {
	struct Neighbour__modeSpecificInfo {
		Neighbour__modeSpecificInfo_PR present;
		union Neighbour__modeSpecificInfo_u {
			struct Neighbour__modeSpecificInfo__fdd {
				struct PrimaryCPICH_Info	*neighbourIdentity	/* OPTIONAL */;
				struct UE_RX_TX_TimeDifferenceType2Info	*uE_RX_TX_TimeDifferenceType2Info	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct Neighbour__modeSpecificInfo__tdd {
				struct CellAndChannelIdentity	*neighbourAndChannelIdentity	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	NeighbourQuality_t	 neighbourQuality;
	SFN_SFN_ObsTimeDifference2_t	 sfn_SFN_ObsTimeDifference2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Neighbour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Neighbour;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/PrimaryCPICH-Info.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-RX-TX-TimeDifferenceType2Info.h"
#include "rf_phreaker/umts_rrc_asn_library/CellAndChannelIdentity.h"

#endif	/* _Neighbour_H_ */
