/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_NetworkAssistedGANSS_Supported_List_H_
#define	_NetworkAssistedGANSS_Supported_List_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include "rf_phreaker/umts_rrc_asn_library/GANSS-Mode.h"
#include "rf_phreaker/umts_rrc_asn_library/GANSS-Signal-Id.h"
#include <rf_phreaker/umts_rrc_asn_library/BOOLEAN.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum gANSS_Id {
	gANSS_Id_sbas	= 0,
	gANSS_Id_modernizedGPS	= 1,
	gANSS_Id_qzss	= 2,
	gANSS_Id_glonass	= 3,
	gANSS_Id_spare4	= 4,
	gANSS_Id_spare3	= 5,
	gANSS_Id_spare2	= 6,
	gANSS_Id_spare1	= 7
} e_gANSS_Id;

/* NetworkAssistedGANSS-Supported-List */
typedef struct NetworkAssistedGANSS_Supported_List {
	A_SEQUENCE_OF(struct NetworkAssistedGANSS_Supported_List__Member {
		long	*gANSS_Id	/* OPTIONAL */;
		GANSS_Mode_t	 gANSS_Mode;
		GANSS_Signal_Id_t	*gANSS_SignalId	/* OPTIONAL */;
		BOOLEAN_t	 supportForUE_GANSS_TimingOfCellFrames;
		BOOLEAN_t	*supportForUE_GANSS_CarrierPhaseMeasurement	/* OPTIONAL */;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NetworkAssistedGANSS_Supported_List_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_gANSS_Id_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NetworkAssistedGANSS_Supported_List;

#ifdef __cplusplus
}
#endif

#endif	/* _NetworkAssistedGANSS_Supported_List_H_ */
