/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PagingType2_H_
#define	_PagingType2_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/PagingCause.h"
#include "rf_phreaker/umts_rrc_asn_library/CN-DomainIdentity.h"
#include "rf_phreaker/umts_rrc_asn_library/PagingRecordTypeID.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PagingType2 */
typedef struct PagingType2 {
	RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
	PagingCause_t	 pagingCause;
	CN_DomainIdentity_t	 cn_DomainIdentity;
	PagingRecordTypeID_t	 pagingRecordTypeID;
	struct PagingType2__laterNonCriticalExtensions {
		BIT_STRING_t	*pagingType2_r3_add_ext	/* OPTIONAL */;
		struct PagingType2__laterNonCriticalExtensions__nonCriticalExtensions {
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laterNonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingType2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PagingType2;

#ifdef __cplusplus
}
#endif

#endif	/* _PagingType2_H_ */
