/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PagingRecord_H_
#define	_PagingRecord_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/PagingCause.h"
#include "rf_phreaker/umts_rrc_asn_library/CN-DomainIdentity.h"
#include "rf_phreaker/umts_rrc_asn_library/CN-PagedUE-Identity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/U-RNTI.h"
#include "rf_phreaker/umts_rrc_asn_library/PagingRecordTypeID.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PagingRecord_PR {
	PagingRecord_PR_NOTHING,	/* No components present */
	PagingRecord_PR_cn_Identity,
	PagingRecord_PR_utran_Identity
} PagingRecord_PR;

/* PagingRecord */
typedef struct PagingRecord {
	PagingRecord_PR present;
	union PagingRecord_u {
		struct PagingRecord__cn_Identity {
			PagingCause_t	 pagingCause;
			CN_DomainIdentity_t	 cn_DomainIdentity;
			CN_PagedUE_Identity_t	 cn_pagedUE_Identity;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} cn_Identity;
		struct PagingRecord__utran_Identity {
			U_RNTI_t	 u_RNTI;
			struct PagingRecord__utran_Identity__cn_OriginatedPage_connectedMode_UE {
				PagingCause_t	 pagingCause;
				CN_DomainIdentity_t	 cn_DomainIdentity;
				PagingRecordTypeID_t	 pagingRecordTypeID;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *cn_OriginatedPage_connectedMode_UE;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} utran_Identity;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PagingRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PagingRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _PagingRecord_H_ */
