/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PDCP_ROHC_TargetMode_H_
#define	_PDCP_ROHC_TargetMode_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_ROHC_TargetMode {
	PDCP_ROHC_TargetMode_o_Mode	= 0,
	PDCP_ROHC_TargetMode_r_Mode	= 1
} e_PDCP_ROHC_TargetMode;

/* PDCP-ROHC-TargetMode */
typedef long	 PDCP_ROHC_TargetMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDCP_ROHC_TargetMode;
asn_struct_free_f PDCP_ROHC_TargetMode_free;
asn_struct_print_f PDCP_ROHC_TargetMode_print;
asn_constr_check_f PDCP_ROHC_TargetMode_constraint;
ber_type_decoder_f PDCP_ROHC_TargetMode_decode_ber;
der_type_encoder_f PDCP_ROHC_TargetMode_encode_der;
xer_type_decoder_f PDCP_ROHC_TargetMode_decode_xer;
xer_type_encoder_f PDCP_ROHC_TargetMode_encode_xer;
per_type_decoder_f PDCP_ROHC_TargetMode_decode_uper;
per_type_encoder_f PDCP_ROHC_TargetMode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_ROHC_TargetMode_H_ */
