/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PhysicalChannelCapability_v920ext_H_
#define	_PhysicalChannelCapability_v920ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DL-PhysChCapabilityFDD-v920ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-PhysChCapabilityFDD-v920ext.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhysicalChannelCapability-v920ext */
typedef struct PhysicalChannelCapability_v920ext {
	struct PhysicalChannelCapability_v920ext__fddPhysChCapability {
		DL_PhysChCapabilityFDD_v920ext_t	 downlinkPhysChCapability;
		UL_PhysChCapabilityFDD_v920ext_t	 uplinkPhysChCapability;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *fddPhysChCapability;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalChannelCapability_v920ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalChannelCapability_v920ext;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalChannelCapability_v920ext_H_ */
