/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PhysicalChannelCapability_H_
#define	_PhysicalChannelCapability_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DL-PhysChCapabilityFDD.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-PhysChCapabilityFDD.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/DL-PhysChCapabilityTDD.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-PhysChCapabilityTDD.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PhysicalChannelCapability */
typedef struct PhysicalChannelCapability {
	struct PhysicalChannelCapability__fddPhysChCapability {
		DL_PhysChCapabilityFDD_t	 downlinkPhysChCapability;
		UL_PhysChCapabilityFDD_t	 uplinkPhysChCapability;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *fddPhysChCapability;
	struct PhysicalChannelCapability__tddPhysChCapability {
		DL_PhysChCapabilityTDD_t	 downlinkPhysChCapability;
		UL_PhysChCapabilityTDD_t	 uplinkPhysChCapability;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *tddPhysChCapability;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalChannelCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalChannelCapability;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysicalChannelCapability_H_ */
