/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PICH_Info_H_
#define	_PICH_Info_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/ChannelisationCode256.h"
#include "rf_phreaker/umts_rrc_asn_library/PI-CountPerFrame.h"
#include <rf_phreaker/umts_rrc_asn_library/BOOLEAN.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/TDD-PICH-CCode.h"
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber.h"
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftAndBurstType.h"
#include "rf_phreaker/umts_rrc_asn_library/PagingIndicatorLength.h"
#include "rf_phreaker/umts_rrc_asn_library/N-GAP.h"
#include "rf_phreaker/umts_rrc_asn_library/N-PCH.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PICH_Info_PR {
	PICH_Info_PR_NOTHING,	/* No components present */
	PICH_Info_PR_fdd,
	PICH_Info_PR_tdd
} PICH_Info_PR;

/* Forward declarations */
struct RepPerLengthOffset_PICH;

/* PICH-Info */
typedef struct PICH_Info {
	PICH_Info_PR present;
	union PICH_Info_u {
		struct PICH_Info__fdd {
			ChannelisationCode256_t	 channelisationCode256;
			PI_CountPerFrame_t	 pi_CountPerFrame;
			BOOLEAN_t	 sttd_Indicator;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} fdd;
		struct PICH_Info__tdd {
			TDD_PICH_CCode_t	*channelisationCode	/* OPTIONAL */;
			TimeslotNumber_t	*timeslot	/* OPTIONAL */;
			MidambleShiftAndBurstType_t	 midambleShiftAndBurstType;
			struct RepPerLengthOffset_PICH	*repetitionPeriodLengthOffset	/* OPTIONAL */;
			PagingIndicatorLength_t	 pagingIndicatorLength	/* DEFAULT 0 */;
			N_GAP_t	*n_GAP	/* DEFAULT 1 */;
			N_PCH_t	*n_PCH	/* DEFAULT 2 */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} tdd;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PICH_Info_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PICH_Info;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/RepPerLengthOffset-PICH.h"

#endif	/* _PICH_Info_H_ */
