/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_PRACH_Information_LCR_H_
#define	_PRACH_Information_LCR_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TimeslotNumber-PRACH-LCR-r4.h"
#include "rf_phreaker/umts_rrc_asn_library/PRACH-ChanCodes-List-LCR.h"
#include "rf_phreaker/umts_rrc_asn_library/MidambleShiftAndBurstType-LCR-r4.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FPACH_Info_r4;

/* PRACH-Information-LCR */
typedef struct PRACH_Information_LCR {
	TimeslotNumber_PRACH_LCR_r4_t	 timeslot;
	PRACH_ChanCodes_List_LCR_t	 prach_ChanCodes_list_LCR;
	MidambleShiftAndBurstType_LCR_r4_t	 midambleShiftAndBurstType;
	struct FPACH_Info_r4	*fpach_Info	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PRACH_Information_LCR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PRACH_Information_LCR;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/FPACH-Info-r4.h"

#endif	/* _PRACH_Information_LCR_H_ */
