/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_RedirectionInfo_H_
#define	_RedirectionInfo_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/FrequencyInfo.h"
#include "rf_phreaker/umts_rrc_asn_library/InterRATInfo.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RedirectionInfo_PR {
	RedirectionInfo_PR_NOTHING,	/* No components present */
	RedirectionInfo_PR_frequencyInfo,
	RedirectionInfo_PR_interRATInfo
} RedirectionInfo_PR;

/* RedirectionInfo */
typedef struct RedirectionInfo {
	RedirectionInfo_PR present;
	union RedirectionInfo_u {
		FrequencyInfo_t	 frequencyInfo;
		InterRATInfo_t	 interRATInfo;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RedirectionInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RedirectionInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _RedirectionInfo_H_ */
