/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_Reference_Beta_16QAM_H_
#define	_Reference_Beta_16QAM_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Reference-Beta-16QAM */
typedef struct Reference_Beta_16QAM {
	long	 reference_Code_Rate;
	long	 reference_Beta;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Reference_Beta_16QAM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Reference_Beta_16QAM;

#ifdef __cplusplus
}
#endif

#endif	/* _Reference_Beta_16QAM_H_ */
