/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_ReqDataBitAssistance_H_
#define	_ReqDataBitAssistance_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DGANSS-Sig-Id-Req.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/asn_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE_OF.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReqDataBitAssistance */
typedef struct ReqDataBitAssistance {
	DGANSS_Sig_Id_Req_t	 ganssSignalID;
	long	 ganssDataBitInterval;
	struct ReqDataBitAssistance__ganssSatelliteInfo {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ganssSatelliteInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReqDataBitAssistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReqDataBitAssistance;

#ifdef __cplusplus
}
#endif

#endif	/* _ReqDataBitAssistance_H_ */
