/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_RF_CapabilityComp_v770ext_H_
#define	_RF_CapabilityComp_v770ext_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RadioFrequencyBandTDDList-r7.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR {
	RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR_NOTHING,	/* No components present */
	RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR_notSupported,
	RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR_supported
} RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR;

/* RF-CapabilityComp-v770ext */
typedef struct RF_CapabilityComp_v770ext {
	RadioFrequencyBandTDDList_r7_t	*tdd384_RF_Capability	/* OPTIONAL */;
	struct RF_CapabilityComp_v770ext__tdd768_RF_Capability {
		RF_CapabilityComp_v770ext__tdd768_RF_Capability_PR present;
		union RF_CapabilityComp_v770ext__tdd768_RF_Capability_u {
			NULL_t	 notSupported;
			RadioFrequencyBandTDDList_r7_t	 supported;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} tdd768_RF_Capability;
	RadioFrequencyBandTDDList_r7_t	*tdd128_RF_Capability	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RF_CapabilityComp_v770ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RF_CapabilityComp_v770ext;

#ifdef __cplusplus
}
#endif

#endif	/* _RF_CapabilityComp_v770ext_H_ */
