/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_RRCConnectionReject_H_
#define	_RRCConnectionReject_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionReject-r3-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionReject-v690ext-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionReject-v6f0ext-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionReject-v860ext-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionReject-vaxyext-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/InitialUE-Identity.h"
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionReject_PR {
	RRCConnectionReject_PR_NOTHING,	/* No components present */
	RRCConnectionReject_PR_r3,
	RRCConnectionReject_PR_later_than_r3
} RRCConnectionReject_PR;

/* RRCConnectionReject */
typedef struct RRCConnectionReject {
	RRCConnectionReject_PR present;
	union RRCConnectionReject_u {
		struct RRCConnectionReject__r3 {
			RRCConnectionReject_r3_IEs_t	 rrcConnectionReject_r3;
			struct RRCConnectionReject__r3__laterNonCriticalExtensions {
				BIT_STRING_t	*rrcConnectionReject_r3_add_ext	/* OPTIONAL */;
				struct RRCConnectionReject__r3__laterNonCriticalExtensions__v690NonCriticalExtensions {
					RRCConnectionReject_v690ext_IEs_t	 rrcConnectionReject_v690ext;
					struct RRCConnectionReject__r3__laterNonCriticalExtensions__v690NonCriticalExtensions__v6f0NonCriticalExtensions {
						RRCConnectionReject_v6f0ext_IEs_t	 rrcConnectionReject_v6f0ext;
						struct RRCConnectionReject__r3__laterNonCriticalExtensions__v690NonCriticalExtensions__v6f0NonCriticalExtensions__v860NonCriticalExtensions {
							RRCConnectionReject_v860ext_IEs_t	 rrcConnectionReject_v860ext;
							struct RRCConnectionReject__r3__laterNonCriticalExtensions__v690NonCriticalExtensions__v6f0NonCriticalExtensions__v860NonCriticalExtensions__vaxyNonCriticalExtensions {
								RRCConnectionReject_vaxyext_IEs_t	 rrcConnectionReject_vaxyext;
								struct RRCConnectionReject__r3__laterNonCriticalExtensions__v690NonCriticalExtensions__v6f0NonCriticalExtensions__v860NonCriticalExtensions__vaxyNonCriticalExtensions__nonCriticalExtensions {
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *nonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *vaxyNonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v860NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *v6f0NonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *v690NonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct RRCConnectionReject__later_than_r3 {
			InitialUE_Identity_t	 initialUE_Identity;
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct RRCConnectionReject__later_than_r3__criticalExtensions {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReject_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReject;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionReject_H_ */
