/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#include <rf_phreaker/umts_rrc_asn_library/asn_internal.h>

#include "rf_phreaker/umts_rrc_asn_library/RRCConnectionSetupComplete.h"

static int
memb_rrcConnectionSetupComplete_r3_add_ext_constraint_12(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_rrcConnectionSetupComplete_r3_add_ext_constr_13 = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER value map */
};
static ber_tlv_tag_t asn_DEF_nonCriticalExtensions_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_nonCriticalExtensions_specs_28 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions__nonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions__nonCriticalExtensions, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_nonCriticalExtensions_28 = {
	"nonCriticalExtensions",
	"nonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_nonCriticalExtensions_tags_28,
	sizeof(asn_DEF_nonCriticalExtensions_tags_28)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_28[0]) - 1, /* 1 */
	asn_DEF_nonCriticalExtensions_tags_28,	/* Same as above */
	sizeof(asn_DEF_nonCriticalExtensions_tags_28)
		/sizeof(asn_DEF_nonCriticalExtensions_tags_28[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* No members */
	&asn_SPC_nonCriticalExtensions_specs_28	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vaxyNonCriticalExtensions_26[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions, rrcConectionSetupComplete_vaxyext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_vaxyext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConectionSetupComplete-vaxyext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions, nonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_nonCriticalExtensions_28,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"nonCriticalExtensions"
		},
};
static int asn_MAP_vaxyNonCriticalExtensions_oms_26[] = { 1 };
static ber_tlv_tag_t asn_DEF_vaxyNonCriticalExtensions_tags_26[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_vaxyNonCriticalExtensions_tag2el_26[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConectionSetupComplete-vaxyext at 8202 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* nonCriticalExtensions at 8203 */
};
static asn_SEQUENCE_specifics_t asn_SPC_vaxyNonCriticalExtensions_specs_26 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions__vaxyNonCriticalExtensions, _asn_ctx),
	asn_MAP_vaxyNonCriticalExtensions_tag2el_26,
	2,	/* Count of tags in the map */
	asn_MAP_vaxyNonCriticalExtensions_oms_26,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vaxyNonCriticalExtensions_26 = {
	"vaxyNonCriticalExtensions",
	"vaxyNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vaxyNonCriticalExtensions_tags_26,
	sizeof(asn_DEF_vaxyNonCriticalExtensions_tags_26)
		/sizeof(asn_DEF_vaxyNonCriticalExtensions_tags_26[0]) - 1, /* 1 */
	asn_DEF_vaxyNonCriticalExtensions_tags_26,	/* Same as above */
	sizeof(asn_DEF_vaxyNonCriticalExtensions_tags_26)
		/sizeof(asn_DEF_vaxyNonCriticalExtensions_tags_26[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_vaxyNonCriticalExtensions_26,
	2,	/* Elements count */
	&asn_SPC_vaxyNonCriticalExtensions_specs_26	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v770NonCriticalExtensions_24[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions, rrcConectionSetupComplete_v770ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v770ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConectionSetupComplete-v770ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions, vaxyNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_vaxyNonCriticalExtensions_26,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"vaxyNonCriticalExtensions"
		},
};
static int asn_MAP_v770NonCriticalExtensions_oms_24[] = { 1 };
static ber_tlv_tag_t asn_DEF_v770NonCriticalExtensions_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v770NonCriticalExtensions_tag2el_24[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConectionSetupComplete-v770ext at 8199 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* vaxyNonCriticalExtensions at 8202 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v770NonCriticalExtensions_specs_24 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__v770NonCriticalExtensions, _asn_ctx),
	asn_MAP_v770NonCriticalExtensions_tag2el_24,
	2,	/* Count of tags in the map */
	asn_MAP_v770NonCriticalExtensions_oms_24,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v770NonCriticalExtensions_24 = {
	"v770NonCriticalExtensions",
	"v770NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v770NonCriticalExtensions_tags_24,
	sizeof(asn_DEF_v770NonCriticalExtensions_tags_24)
		/sizeof(asn_DEF_v770NonCriticalExtensions_tags_24[0]) - 1, /* 1 */
	asn_DEF_v770NonCriticalExtensions_tags_24,	/* Same as above */
	sizeof(asn_DEF_v770NonCriticalExtensions_tags_24)
		/sizeof(asn_DEF_v770NonCriticalExtensions_tags_24[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v770NonCriticalExtensions_24,
	2,	/* Elements count */
	&asn_SPC_v770NonCriticalExtensions_specs_24	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v690NonCriticalExtensions_22[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions, rrcConnectionSetupComplete_v690ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v690ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v690ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions, v770NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v770NonCriticalExtensions_24,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v770NonCriticalExtensions"
		},
};
static int asn_MAP_v690NonCriticalExtensions_oms_22[] = { 1 };
static ber_tlv_tag_t asn_DEF_v690NonCriticalExtensions_tags_22[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v690NonCriticalExtensions_tag2el_22[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v690ext at 8196 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v770NonCriticalExtensions at 8199 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v690NonCriticalExtensions_specs_22 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions, _asn_ctx),
	asn_MAP_v690NonCriticalExtensions_tag2el_22,
	2,	/* Count of tags in the map */
	asn_MAP_v690NonCriticalExtensions_oms_22,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v690NonCriticalExtensions_22 = {
	"v690NonCriticalExtensions",
	"v690NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v690NonCriticalExtensions_tags_22,
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_22)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_22[0]) - 1, /* 1 */
	asn_DEF_v690NonCriticalExtensions_tags_22,	/* Same as above */
	sizeof(asn_DEF_v690NonCriticalExtensions_tags_22)
		/sizeof(asn_DEF_v690NonCriticalExtensions_tags_22[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v690NonCriticalExtensions_22,
	2,	/* Elements count */
	&asn_SPC_v690NonCriticalExtensions_specs_22	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v5c0NonCriticalExtensions_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions, rrcConnectionSetupComplete_v5c0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v5c0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v5c0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions, v690NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v690NonCriticalExtensions_22,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v690NonCriticalExtensions"
		},
};
static int asn_MAP_v5c0NonCriticalExtensions_oms_20[] = { 1 };
static ber_tlv_tag_t asn_DEF_v5c0NonCriticalExtensions_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v5c0NonCriticalExtensions_tag2el_20[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v5c0ext at 8193 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v690NonCriticalExtensions at 8196 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v5c0NonCriticalExtensions_specs_20 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v5c0NonCriticalExtensions_tag2el_20,
	2,	/* Count of tags in the map */
	asn_MAP_v5c0NonCriticalExtensions_oms_20,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v5c0NonCriticalExtensions_20 = {
	"v5c0NonCriticalExtensions",
	"v5c0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v5c0NonCriticalExtensions_tags_20,
	sizeof(asn_DEF_v5c0NonCriticalExtensions_tags_20)
		/sizeof(asn_DEF_v5c0NonCriticalExtensions_tags_20[0]) - 1, /* 1 */
	asn_DEF_v5c0NonCriticalExtensions_tags_20,	/* Same as above */
	sizeof(asn_DEF_v5c0NonCriticalExtensions_tags_20)
		/sizeof(asn_DEF_v5c0NonCriticalExtensions_tags_20[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v5c0NonCriticalExtensions_20,
	2,	/* Elements count */
	&asn_SPC_v5c0NonCriticalExtensions_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v590NonCriticalExtensions_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, rrcConnectionSetupComplete_v590ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v590ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v590ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, v5c0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v5c0NonCriticalExtensions_20,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v5c0NonCriticalExtensions"
		},
};
static int asn_MAP_v590NonCriticalExtensions_oms_18[] = { 1 };
static ber_tlv_tag_t asn_DEF_v590NonCriticalExtensions_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v590NonCriticalExtensions_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v590ext at 8190 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v5c0NonCriticalExtensions at 8193 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v590NonCriticalExtensions_specs_18 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions, _asn_ctx),
	asn_MAP_v590NonCriticalExtensions_tag2el_18,
	2,	/* Count of tags in the map */
	asn_MAP_v590NonCriticalExtensions_oms_18,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v590NonCriticalExtensions_18 = {
	"v590NonCriticalExtensions",
	"v590NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v590NonCriticalExtensions_tags_18,
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_18)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_18[0]) - 1, /* 1 */
	asn_DEF_v590NonCriticalExtensions_tags_18,	/* Same as above */
	sizeof(asn_DEF_v590NonCriticalExtensions_tags_18)
		/sizeof(asn_DEF_v590NonCriticalExtensions_tags_18[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v590NonCriticalExtensions_18,
	2,	/* Elements count */
	&asn_SPC_v590NonCriticalExtensions_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v4b0NonCriticalExtensions_16[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions, rrcConnectionSetupComplete_v4b0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v4b0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v4b0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions, v590NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v590NonCriticalExtensions_18,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v590NonCriticalExtensions"
		},
};
static int asn_MAP_v4b0NonCriticalExtensions_oms_16[] = { 1 };
static ber_tlv_tag_t asn_DEF_v4b0NonCriticalExtensions_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v4b0NonCriticalExtensions_tag2el_16[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v4b0ext at 8187 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v590NonCriticalExtensions at 8190 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v4b0NonCriticalExtensions_specs_16 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions__v4b0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v4b0NonCriticalExtensions_tag2el_16,
	2,	/* Count of tags in the map */
	asn_MAP_v4b0NonCriticalExtensions_oms_16,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v4b0NonCriticalExtensions_16 = {
	"v4b0NonCriticalExtensions",
	"v4b0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v4b0NonCriticalExtensions_tags_16,
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_16[0]) - 1, /* 1 */
	asn_DEF_v4b0NonCriticalExtensions_tags_16,	/* Same as above */
	sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_16)
		/sizeof(asn_DEF_v4b0NonCriticalExtensions_tags_16[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v4b0NonCriticalExtensions_16,
	2,	/* Elements count */
	&asn_SPC_v4b0NonCriticalExtensions_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v3g0NonCriticalExtensions_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions, rrcConnectionSetupComplete_v3g0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v3g0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v3g0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions, v4b0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v4b0NonCriticalExtensions_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v4b0NonCriticalExtensions"
		},
};
static int asn_MAP_v3g0NonCriticalExtensions_oms_14[] = { 1 };
static ber_tlv_tag_t asn_DEF_v3g0NonCriticalExtensions_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v3g0NonCriticalExtensions_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v3g0ext at 8184 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v4b0NonCriticalExtensions at 8187 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v3g0NonCriticalExtensions_specs_14 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v3g0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v3g0NonCriticalExtensions_tag2el_14,
	2,	/* Count of tags in the map */
	asn_MAP_v3g0NonCriticalExtensions_oms_14,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v3g0NonCriticalExtensions_14 = {
	"v3g0NonCriticalExtensions",
	"v3g0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v3g0NonCriticalExtensions_tags_14,
	sizeof(asn_DEF_v3g0NonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_v3g0NonCriticalExtensions_tags_14[0]) - 1, /* 1 */
	asn_DEF_v3g0NonCriticalExtensions_tags_14,	/* Same as above */
	sizeof(asn_DEF_v3g0NonCriticalExtensions_tags_14)
		/sizeof(asn_DEF_v3g0NonCriticalExtensions_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v3g0NonCriticalExtensions_14,
	2,	/* Elements count */
	&asn_SPC_v3g0NonCriticalExtensions_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_laterNonCriticalExtensions_12[] = {
	{ ATF_POINTER, 2, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions, rrcConnectionSetupComplete_r3_add_ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_rrcConnectionSetupComplete_r3_add_ext_constraint_12,
		&asn_PER_memb_rrcConnectionSetupComplete_r3_add_ext_constr_13,
		0,
		"rrcConnectionSetupComplete-r3-add-ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions, v3g0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v3g0NonCriticalExtensions_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v3g0NonCriticalExtensions"
		},
};
static int asn_MAP_laterNonCriticalExtensions_oms_12[] = { 0, 1 };
static ber_tlv_tag_t asn_DEF_laterNonCriticalExtensions_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_laterNonCriticalExtensions_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-r3-add-ext at 8182 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v3g0NonCriticalExtensions at 8184 */
};
static asn_SEQUENCE_specifics_t asn_SPC_laterNonCriticalExtensions_specs_12 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions, _asn_ctx),
	asn_MAP_laterNonCriticalExtensions_tag2el_12,
	2,	/* Count of tags in the map */
	asn_MAP_laterNonCriticalExtensions_oms_12,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_laterNonCriticalExtensions_12 = {
	"laterNonCriticalExtensions",
	"laterNonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_laterNonCriticalExtensions_tags_12,
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_12[0]) - 1, /* 1 */
	asn_DEF_laterNonCriticalExtensions_tags_12,	/* Same as above */
	sizeof(asn_DEF_laterNonCriticalExtensions_tags_12)
		/sizeof(asn_DEF_laterNonCriticalExtensions_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_laterNonCriticalExtensions_12,
	2,	/* Elements count */
	&asn_SPC_laterNonCriticalExtensions_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v3a0NonCriticalExtensions_10[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions, rrcConnectionSetupComplete_v3a0ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v3a0ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v3a0ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions, laterNonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_laterNonCriticalExtensions_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"laterNonCriticalExtensions"
		},
};
static int asn_MAP_v3a0NonCriticalExtensions_oms_10[] = { 1 };
static ber_tlv_tag_t asn_DEF_v3a0NonCriticalExtensions_tags_10[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v3a0NonCriticalExtensions_tag2el_10[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v3a0ext at 8178 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* laterNonCriticalExtensions at 8182 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v3a0NonCriticalExtensions_specs_10 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions, _asn_ctx),
	asn_MAP_v3a0NonCriticalExtensions_tag2el_10,
	2,	/* Count of tags in the map */
	asn_MAP_v3a0NonCriticalExtensions_oms_10,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v3a0NonCriticalExtensions_10 = {
	"v3a0NonCriticalExtensions",
	"v3a0NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v3a0NonCriticalExtensions_tags_10,
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_10[0]) - 1, /* 1 */
	asn_DEF_v3a0NonCriticalExtensions_tags_10,	/* Same as above */
	sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_10)
		/sizeof(asn_DEF_v3a0NonCriticalExtensions_tags_10[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v3a0NonCriticalExtensions_10,
	2,	/* Elements count */
	&asn_SPC_v3a0NonCriticalExtensions_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v380NonCriticalExtensions_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions, rrcConnectionSetupComplete_v380ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v380ext_IEs,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v380ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions, v3a0NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v3a0NonCriticalExtensions_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v3a0NonCriticalExtensions"
		},
};
static int asn_MAP_v380NonCriticalExtensions_oms_8[] = { 1 };
static ber_tlv_tag_t asn_DEF_v380NonCriticalExtensions_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v380NonCriticalExtensions_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v380ext at 8175 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v3a0NonCriticalExtensions at 8178 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v380NonCriticalExtensions_specs_8 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions__v380NonCriticalExtensions, _asn_ctx),
	asn_MAP_v380NonCriticalExtensions_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_v380NonCriticalExtensions_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v380NonCriticalExtensions_8 = {
	"v380NonCriticalExtensions",
	"v380NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v380NonCriticalExtensions_tags_8,
	sizeof(asn_DEF_v380NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v380NonCriticalExtensions_tags_8[0]) - 1, /* 1 */
	asn_DEF_v380NonCriticalExtensions_tags_8,	/* Same as above */
	sizeof(asn_DEF_v380NonCriticalExtensions_tags_8)
		/sizeof(asn_DEF_v380NonCriticalExtensions_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v380NonCriticalExtensions_8,
	2,	/* Elements count */
	&asn_SPC_v380NonCriticalExtensions_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_v370NonCriticalExtensions_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions, rrcConnectionSetupComplete_v370ext),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRCConnectionSetupComplete_v370ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrcConnectionSetupComplete-v370ext"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions, v380NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_v380NonCriticalExtensions_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v380NonCriticalExtensions"
		},
};
static int asn_MAP_v370NonCriticalExtensions_oms_6[] = { 1 };
static ber_tlv_tag_t asn_DEF_v370NonCriticalExtensions_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_v370NonCriticalExtensions_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrcConnectionSetupComplete-v370ext at 8173 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* v380NonCriticalExtensions at 8175 */
};
static asn_SEQUENCE_specifics_t asn_SPC_v370NonCriticalExtensions_specs_6 = {
	sizeof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions),
	offsetof(struct RRCConnectionSetupComplete__v370NonCriticalExtensions, _asn_ctx),
	asn_MAP_v370NonCriticalExtensions_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_v370NonCriticalExtensions_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_v370NonCriticalExtensions_6 = {
	"v370NonCriticalExtensions",
	"v370NonCriticalExtensions",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_v370NonCriticalExtensions_tags_6,
	sizeof(asn_DEF_v370NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v370NonCriticalExtensions_tags_6[0]) - 1, /* 1 */
	asn_DEF_v370NonCriticalExtensions_tags_6,	/* Same as above */
	sizeof(asn_DEF_v370NonCriticalExtensions_tags_6)
		/sizeof(asn_DEF_v370NonCriticalExtensions_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_v370NonCriticalExtensions_6,
	2,	/* Elements count */
	&asn_SPC_v370NonCriticalExtensions_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RRCConnectionSetupComplete_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete, rrc_TransactionIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RRC_TransactionIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rrc-TransactionIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionSetupComplete, startList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_STARTList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"startList"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCConnectionSetupComplete, ue_RadioAccessCapability),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UE_RadioAccessCapability,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ue-RadioAccessCapability"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCConnectionSetupComplete, ue_RATSpecificCapability),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InterRAT_UE_RadioAccessCapabilityList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ue-RATSpecificCapability"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionSetupComplete, v370NonCriticalExtensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_v370NonCriticalExtensions_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"v370NonCriticalExtensions"
		},
};
static int asn_MAP_RRCConnectionSetupComplete_oms_1[] = { 2, 3, 4 };
static ber_tlv_tag_t asn_DEF_RRCConnectionSetupComplete_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RRCConnectionSetupComplete_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rrc-TransactionIdentifier at 8166 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* startList at 8167 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ue-RadioAccessCapability at 8168 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ue-RATSpecificCapability at 8170 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* v370NonCriticalExtensions at 8173 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionSetupComplete_specs_1 = {
	sizeof(struct RRCConnectionSetupComplete),
	offsetof(struct RRCConnectionSetupComplete, _asn_ctx),
	asn_MAP_RRCConnectionSetupComplete_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RRCConnectionSetupComplete_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionSetupComplete = {
	"RRCConnectionSetupComplete",
	"RRCConnectionSetupComplete",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RRCConnectionSetupComplete_tags_1,
	sizeof(asn_DEF_RRCConnectionSetupComplete_tags_1)
		/sizeof(asn_DEF_RRCConnectionSetupComplete_tags_1[0]), /* 1 */
	asn_DEF_RRCConnectionSetupComplete_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCConnectionSetupComplete_tags_1)
		/sizeof(asn_DEF_RRCConnectionSetupComplete_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RRCConnectionSetupComplete_1,
	5,	/* Elements count */
	&asn_SPC_RRCConnectionSetupComplete_specs_1	/* Additional specs */
};

