/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SCCPCH_SystemInformation_H_
#define	_SCCPCH_SystemInformation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/SecondaryCCPCH-Info.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TFCS;
struct FACH_PCH_InformationList;
struct PICH_Info;

/* SCCPCH-SystemInformation */
typedef struct SCCPCH_SystemInformation {
	SecondaryCCPCH_Info_t	 secondaryCCPCH_Info;
	struct TFCS	*tfcs	/* OPTIONAL */;
	struct FACH_PCH_InformationList	*fach_PCH_InformationList	/* OPTIONAL */;
	struct PICH_Info	*pich_Info	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCCPCH_SystemInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCCPCH_SystemInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/TFCS.h"
#include "rf_phreaker/umts_rrc_asn_library/FACH-PCH-InformationList.h"
#include "rf_phreaker/umts_rrc_asn_library/PICH-Info.h"

#endif	/* _SCCPCH_SystemInformation_H_ */
