/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SecondaryCellMIMOparametersFDD_r10_H_
#define	_SecondaryCellMIMOparametersFDD_r10_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/MIMO-N-M-Ratio.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryCellMIMOparametersFDD_r10_PR {
	SecondaryCellMIMOparametersFDD_r10_PR_NOTHING,	/* No components present */
	SecondaryCellMIMOparametersFDD_r10_PR_continue,
	SecondaryCellMIMOparametersFDD_r10_PR_newConfiguration
} SecondaryCellMIMOparametersFDD_r10_PR;
typedef enum SecondaryCellMIMOparametersFDD_r10__newConfiguration__precodingWeightSetRestriction {
	SecondaryCellMIMOparametersFDD_r10__newConfiguration__precodingWeightSetRestriction_true	= 0
} e_SecondaryCellMIMOparametersFDD_r10__newConfiguration__precodingWeightSetRestriction;

/* Forward declarations */
struct MIMO_PilotConfiguration_r9;

/* SecondaryCellMIMOparametersFDD-r10 */
typedef struct SecondaryCellMIMOparametersFDD_r10 {
	SecondaryCellMIMOparametersFDD_r10_PR present;
	union SecondaryCellMIMOparametersFDD_r10_u {
		NULL_t	 Continue;
		struct SecondaryCellMIMOparametersFDD_r10__newConfiguration {
			MIMO_N_M_Ratio_t	*mimoN_M_Ratio	/* OPTIONAL */;
			struct MIMO_PilotConfiguration_r9	*mimoPilotConfiguration	/* OPTIONAL */;
			long	*precodingWeightSetRestriction	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} newConfiguration;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecondaryCellMIMOparametersFDD_r10_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_precodingWeightSetRestriction_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryCellMIMOparametersFDD_r10;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/MIMO-PilotConfiguration-r9.h"

#endif	/* _SecondaryCellMIMOparametersFDD_r10_H_ */
