/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SecondaryEDCH_Info_Common_H_
#define	_SecondaryEDCH_Info_Common_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/FrequencyInfo.h"
#include "rf_phreaker/umts_rrc_asn_library/ScramblingCodeType.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-ScramblingCode.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/MinReduced-E-DPDCH-GainFactor.h"
#include "rf_phreaker/umts_rrc_asn_library/E-DCH-MinimumSet-E-TFCI.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/umts_rrc_asn_library/PC-Preamble.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecondaryEDCH_Info_Common__servingGrant__primary_Secondary_GrantSelector {
	SecondaryEDCH_Info_Common__servingGrant__primary_Secondary_GrantSelector_primary	= 0,
	SecondaryEDCH_Info_Common__servingGrant__primary_Secondary_GrantSelector_secondary	= 1
} e_SecondaryEDCH_Info_Common__servingGrant__primary_Secondary_GrantSelector;

/* SecondaryEDCH-Info-Common */
typedef struct SecondaryEDCH_Info_Common {
	FrequencyInfo_t	 frequencyInfo;
	ScramblingCodeType_t	 scramblingCodeType;
	UL_ScramblingCode_t	 scramblingCodeNumber;
	BIT_STRING_t	*ms2_SchedTransmGrantHARQAlloc	/* OPTIONAL */;
	struct SecondaryEDCH_Info_Common__servingGrant {
		long	 primary_Secondary_GrantSelector;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *servingGrant;
	MinReduced_E_DPDCH_GainFactor_t	*minReduced_E_DPDCH_GainFactor	/* OPTIONAL */;
	E_DCH_MinimumSet_E_TFCI_t	*e_DCH_minimumSet_E_TFCI	/* OPTIONAL */;
	long	 dpcchPowerOffset_SecondaryULFrequency;
	PC_Preamble_t	 pc_Preamble;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecondaryEDCH_Info_Common_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_primary_Secondary_GrantSelector_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SecondaryEDCH_Info_Common;

#ifdef __cplusplus
}
#endif

#endif	/* _SecondaryEDCH_Info_Common_H_ */
