/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SecurityModeCommand_H_
#define	_SecurityModeCommand_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/SecurityModeCommand-r3-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/SecurityModeCommand-r7-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SecurityModeCommand_PR {
	SecurityModeCommand_PR_NOTHING,	/* No components present */
	SecurityModeCommand_PR_r3,
	SecurityModeCommand_PR_later_than_r3
} SecurityModeCommand_PR;
typedef enum SecurityModeCommand__later_than_r3__criticalExtensions_PR {
	SecurityModeCommand__later_than_r3__criticalExtensions_PR_NOTHING,	/* No components present */
	SecurityModeCommand__later_than_r3__criticalExtensions_PR_r7,
	SecurityModeCommand__later_than_r3__criticalExtensions_PR_criticalExtensions
} SecurityModeCommand__later_than_r3__criticalExtensions_PR;

/* SecurityModeCommand */
typedef struct SecurityModeCommand {
	SecurityModeCommand_PR present;
	union SecurityModeCommand_u {
		struct SecurityModeCommand__r3 {
			SecurityModeCommand_r3_IEs_t	 securityModeCommand_r3;
			struct SecurityModeCommand__r3__laterNonCriticalExtensions {
				BIT_STRING_t	*securityModeCommand_r3_add_ext	/* OPTIONAL */;
				struct SecurityModeCommand__r3__laterNonCriticalExtensions__nonCriticalExtensions {
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *nonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *laterNonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct SecurityModeCommand__later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct SecurityModeCommand__later_than_r3__criticalExtensions {
				SecurityModeCommand__later_than_r3__criticalExtensions_PR present;
				union SecurityModeCommand__later_than_r3__criticalExtensions_u {
					struct SecurityModeCommand__later_than_r3__criticalExtensions__r7 {
						SecurityModeCommand_r7_IEs_t	 securityModeCommand_r7;
						BIT_STRING_t	*securityModeCommand_r7_add_ext	/* OPTIONAL */;
						struct SecurityModeCommand__later_than_r3__criticalExtensions__r7__nonCriticalExtensions {
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *nonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r7;
					struct SecurityModeCommand__later_than_r3__criticalExtensions__criticalExtensions {
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityModeCommand_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityModeCommand;

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityModeCommand_H_ */
