/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_ServingCellChangeMsgType_H_
#define	_ServingCellChangeMsgType_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServingCellChangeMsgType {
	ServingCellChangeMsgType_radioBearerSetup	= 0,
	ServingCellChangeMsgType_radioBearerReconfiguration	= 1,
	ServingCellChangeMsgType_transportChannelReconfiguration	= 2,
	ServingCellChangeMsgType_physicalChannelReconfiguration	= 3
} e_ServingCellChangeMsgType;

/* ServingCellChangeMsgType */
typedef long	 ServingCellChangeMsgType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServingCellChangeMsgType;
asn_struct_free_f ServingCellChangeMsgType_free;
asn_struct_print_f ServingCellChangeMsgType_print;
asn_constr_check_f ServingCellChangeMsgType_constraint;
ber_type_decoder_f ServingCellChangeMsgType_decode_ber;
der_type_encoder_f ServingCellChangeMsgType_encode_der;
xer_type_decoder_f ServingCellChangeMsgType_decode_xer;
xer_type_encoder_f ServingCellChangeMsgType_encode_xer;
per_type_decoder_f ServingCellChangeMsgType_decode_uper;
per_type_encoder_f ServingCellChangeMsgType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServingCellChangeMsgType_H_ */
