/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SignallingConnectionReleaseIndication_H_
#define	_SignallingConnectionReleaseIndication_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/CN-DomainIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/SignallingConnectionReleaseIndication-v860ext.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignallingConnectionReleaseIndication */
typedef struct SignallingConnectionReleaseIndication {
	CN_DomainIdentity_t	 cn_DomainIdentity;
	struct SignallingConnectionReleaseIndication__laterNonCriticalExtensions {
		BIT_STRING_t	*signallingConnectionReleaseIndication_r3_add_ext	/* OPTIONAL */;
		struct SignallingConnectionReleaseIndication__laterNonCriticalExtensions__v860nonCriticalExtentions {
			SignallingConnectionReleaseIndication_v860ext_t	 signallingConnectionReleaseIndication_v860ext;
			struct SignallingConnectionReleaseIndication__laterNonCriticalExtensions__v860nonCriticalExtentions__nonCriticalExtensions {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *v860nonCriticalExtentions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *laterNonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignallingConnectionReleaseIndication_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignallingConnectionReleaseIndication;

#ifdef __cplusplus
}
#endif

#endif	/* _SignallingConnectionReleaseIndication_H_ */
