/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SysInfoType8_H_
#define	_SysInfoType8_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/CPCH-Parameters.h"
#include "rf_phreaker/umts_rrc_asn_library/CPCH-SetInfoList.h"
#include "rf_phreaker/umts_rrc_asn_library/CSICH-PowerOffset.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SysInfoType8 */
typedef struct SysInfoType8 {
	CPCH_Parameters_t	 dummy1;
	CPCH_SetInfoList_t	 dummy2;
	CSICH_PowerOffset_t	 dummy3;
	struct SysInfoType8__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType8_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType8;

#ifdef __cplusplus
}
#endif

#endif	/* _SysInfoType8_H_ */
