/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SysInfoType15_3bis_v860ext_IEs_H_
#define	_SysInfoType15_3bis_v860ext_IEs_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_Positioning_GANSS_Almanac_v860ext;
struct UE_Positioning_GANSS_AddUTCModels;
struct UE_Positioning_GANSS_AuxiliaryInfo;

/* SysInfoType15-3bis-v860ext-IEs */
typedef struct SysInfoType15_3bis_v860ext_IEs {
	struct UE_Positioning_GANSS_Almanac_v860ext	*ue_Positioning_GANSS_Almanac	/* OPTIONAL */;
	struct UE_Positioning_GANSS_AddUTCModels	*ue_Positioning_GANSS_AddUTCModels	/* OPTIONAL */;
	struct UE_Positioning_GANSS_AuxiliaryInfo	*ue_Positioning_GANSS_AuxiliaryInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType15_3bis_v860ext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType15_3bis_v860ext_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-Almanac-v860ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-AddUTCModels.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-AuxiliaryInfo.h"

#endif	/* _SysInfoType15_3bis_v860ext_IEs_H_ */
