/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SysInfoType7_H_
#define	_SysInfoType7_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DynamicPersistenceLevelList.h"
#include "rf_phreaker/umts_rrc_asn_library/ExpirationTimeFactor.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/UL-Interference.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SysInfoType7__modeSpecificInfo_PR {
	SysInfoType7__modeSpecificInfo_PR_NOTHING,	/* No components present */
	SysInfoType7__modeSpecificInfo_PR_fdd,
	SysInfoType7__modeSpecificInfo_PR_tdd
} SysInfoType7__modeSpecificInfo_PR;

/* Forward declarations */
struct DynamicPersistenceLevelList;

/* SysInfoType7 */
typedef struct SysInfoType7 {
	struct SysInfoType7__modeSpecificInfo {
		SysInfoType7__modeSpecificInfo_PR present;
		union SysInfoType7__modeSpecificInfo_u {
			struct SysInfoType7__modeSpecificInfo__fdd {
				UL_Interference_t	 ul_Interference;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			NULL_t	 tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	DynamicPersistenceLevelList_t	 prach_Information_SIB5_List;
	struct DynamicPersistenceLevelList	*prach_Information_SIB6_List	/* OPTIONAL */;
	ExpirationTimeFactor_t	*expirationTimeFactor	/* OPTIONAL */;
	struct SysInfoType7__nonCriticalExtensions {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType7;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/DynamicPersistenceLevelList.h"

#endif	/* _SysInfoType7_H_ */
