/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_SysInfoType15_3bis_vaxyext_IEs_H_
#define	_SysInfoType15_3bis_vaxyext_IEs_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_Positioning_GANSS_Almanac_vaxyext;
struct UE_Positioning_GANSS_TimeModels_vaxyext;

/* SysInfoType15-3bis-vaxyext-IEs */
typedef struct SysInfoType15_3bis_vaxyext_IEs {
	struct UE_Positioning_GANSS_Almanac_vaxyext	*ue_Positioning_GANSS_Almanac	/* OPTIONAL */;
	struct UE_Positioning_GANSS_TimeModels_vaxyext	*ue_positioning_GANSS_TimeModels	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SysInfoType15_3bis_vaxyext_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SysInfoType15_3bis_vaxyext_IEs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-Almanac-vaxyext.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GANSS-TimeModels-vaxyext.h"

#endif	/* _SysInfoType15_3bis_vaxyext_IEs_H_ */
