/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_T_CPCH_H_
#define	_T_CPCH_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum T_CPCH {
	T_CPCH_ct0	= 0,
	T_CPCH_ct1	= 1
} e_T_CPCH;

/* T-CPCH */
typedef long	 T_CPCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T_CPCH;
asn_struct_free_f T_CPCH_free;
asn_struct_print_f T_CPCH_print;
asn_constr_check_f T_CPCH_constraint;
ber_type_decoder_f T_CPCH_decode_ber;
der_type_encoder_f T_CPCH_encode_der;
xer_type_decoder_f T_CPCH_decode_xer;
xer_type_encoder_f T_CPCH_encode_xer;
per_type_decoder_f T_CPCH_decode_uper;
per_type_encoder_f T_CPCH_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _T_CPCH_H_ */
