/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_TFC_Value_H_
#define	_TFC_Value_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TFC-Value */
typedef long	 TFC_Value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TFC_Value;
asn_struct_free_f TFC_Value_free;
asn_struct_print_f TFC_Value_print;
asn_constr_check_f TFC_Value_constraint;
ber_type_decoder_f TFC_Value_decode_ber;
der_type_encoder_f TFC_Value_encode_der;
xer_type_decoder_f TFC_Value_decode_xer;
xer_type_encoder_f TFC_Value_encode_xer;
per_type_decoder_f TFC_Value_decode_uper;
per_type_encoder_f TFC_Value_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TFC_Value_H_ */
