/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_TGPS_ConfigurationParams_H_
#define	_TGPS_ConfigurationParams_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TGMP.h"
#include "rf_phreaker/umts_rrc_asn_library/TGPRC.h"
#include "rf_phreaker/umts_rrc_asn_library/TGSN.h"
#include "rf_phreaker/umts_rrc_asn_library/TGL.h"
#include "rf_phreaker/umts_rrc_asn_library/TGD.h"
#include "rf_phreaker/umts_rrc_asn_library/TGPL.h"
#include "rf_phreaker/umts_rrc_asn_library/RPP.h"
#include "rf_phreaker/umts_rrc_asn_library/ITP.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-DL-Mode.h"
#include "rf_phreaker/umts_rrc_asn_library/DL-FrameType.h"
#include "rf_phreaker/umts_rrc_asn_library/DeltaSIR.h"
#include "rf_phreaker/umts_rrc_asn_library/NidentifyAbort.h"
#include "rf_phreaker/umts_rrc_asn_library/TreconfirmAbort.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TGPS-ConfigurationParams */
typedef struct TGPS_ConfigurationParams {
	TGMP_t	 tgmp;
	TGPRC_t	 tgprc;
	TGSN_t	 tgsn;
	TGL_t	 tgl1;
	TGL_t	*tgl2	/* OPTIONAL */;
	TGD_t	 tgd;
	TGPL_t	 tgpl1;
	TGPL_t	*dummy	/* OPTIONAL */;
	RPP_t	 rpp;
	ITP_t	 itp;
	UL_DL_Mode_t	 ul_DL_Mode;
	DL_FrameType_t	 dl_FrameType;
	DeltaSIR_t	 deltaSIR1;
	DeltaSIR_t	 deltaSIRAfter1;
	DeltaSIR_t	*deltaSIR2	/* OPTIONAL */;
	DeltaSIR_t	*deltaSIRAfter2	/* OPTIONAL */;
	NidentifyAbort_t	*nidentifyAbort	/* OPTIONAL */;
	TreconfirmAbort_t	*treconfirmAbort	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TGPS_ConfigurationParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TGPS_ConfigurationParams;

#ifdef __cplusplus
}
#endif

#endif	/* _TGPS_ConfigurationParams_H_ */
