/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_TransportFormatSet_LCR_H_
#define	_TransportFormatSet_LCR_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/DedicatedTransChTFS.h"
#include "rf_phreaker/umts_rrc_asn_library/CommonTransChTFS-LCR.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransportFormatSet_LCR_PR {
	TransportFormatSet_LCR_PR_NOTHING,	/* No components present */
	TransportFormatSet_LCR_PR_dedicatedTransChTFS,
	TransportFormatSet_LCR_PR_commonTransChTFS_LCR
} TransportFormatSet_LCR_PR;

/* TransportFormatSet-LCR */
typedef struct TransportFormatSet_LCR {
	TransportFormatSet_LCR_PR present;
	union TransportFormatSet_LCR_u {
		DedicatedTransChTFS_t	 dedicatedTransChTFS;
		CommonTransChTFS_LCR_t	 commonTransChTFS_LCR;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransportFormatSet_LCR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransportFormatSet_LCR;

#ifdef __cplusplus
}
#endif

#endif	/* _TransportFormatSet_LCR_H_ */
