/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_TransportChannelIdentityDCHandDSCH_H_
#define	_TransportChannelIdentityDCHandDSCH_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TransportChannelIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TransportChannelIdentityDCHandDSCH */
typedef struct TransportChannelIdentityDCHandDSCH {
	TransportChannelIdentity_t	 dch_transport_ch_id;
	TransportChannelIdentity_t	 dsch_transport_ch_id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransportChannelIdentityDCHandDSCH_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransportChannelIdentityDCHandDSCH;

#ifdef __cplusplus
}
#endif

#endif	/* _TransportChannelIdentityDCHandDSCH_H_ */
