/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UE_InternalEventResults_H_
#define	_UE_InternalEventResults_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/PrimaryCPICH-Info.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_InternalEventResults_PR {
	UE_InternalEventResults_PR_NOTHING,	/* No components present */
	UE_InternalEventResults_PR_event6a,
	UE_InternalEventResults_PR_event6b,
	UE_InternalEventResults_PR_event6c,
	UE_InternalEventResults_PR_event6d,
	UE_InternalEventResults_PR_event6e,
	UE_InternalEventResults_PR_event6f,
	UE_InternalEventResults_PR_event6g,
	UE_InternalEventResults_PR_spare
} UE_InternalEventResults_PR;

/* UE-InternalEventResults */
typedef struct UE_InternalEventResults {
	UE_InternalEventResults_PR present;
	union UE_InternalEventResults_u {
		NULL_t	 event6a;
		NULL_t	 event6b;
		NULL_t	 event6c;
		NULL_t	 event6d;
		NULL_t	 event6e;
		PrimaryCPICH_Info_t	 event6f;
		PrimaryCPICH_Info_t	 event6g;
		NULL_t	 spare;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_InternalEventResults_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_InternalEventResults;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_InternalEventResults_H_ */
