/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UE_InternalMeasuredResults_H_
#define	_UE_InternalMeasuredResults_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UE-TransmittedPower.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/UL-TimingAdvance.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_InternalMeasuredResults__modeSpecificInfo_PR {
	UE_InternalMeasuredResults__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UE_InternalMeasuredResults__modeSpecificInfo_PR_fdd,
	UE_InternalMeasuredResults__modeSpecificInfo_PR_tdd
} UE_InternalMeasuredResults__modeSpecificInfo_PR;

/* Forward declarations */
struct UE_RX_TX_ReportEntryList;
struct UE_TransmittedPowerTDD_List;

/* UE-InternalMeasuredResults */
typedef struct UE_InternalMeasuredResults {
	struct UE_InternalMeasuredResults__modeSpecificInfo {
		UE_InternalMeasuredResults__modeSpecificInfo_PR present;
		union UE_InternalMeasuredResults__modeSpecificInfo_u {
			struct UE_InternalMeasuredResults__modeSpecificInfo__fdd {
				UE_TransmittedPower_t	*ue_TransmittedPowerFDD	/* OPTIONAL */;
				struct UE_RX_TX_ReportEntryList	*ue_RX_TX_ReportEntryList	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct UE_InternalMeasuredResults__modeSpecificInfo__tdd {
				struct UE_TransmittedPowerTDD_List	*ue_TransmittedPowerTDD_List	/* OPTIONAL */;
				UL_TimingAdvance_t	*appliedTA	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_InternalMeasuredResults_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_InternalMeasuredResults;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UE-RX-TX-ReportEntryList.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-TransmittedPowerTDD-List.h"

#endif	/* _UE_InternalMeasuredResults_H_ */
