/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UE_Positioning_GPS_ReferenceTime_r7_H_
#define	_UE_Positioning_GPS_ReferenceTime_r7_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include "rf_phreaker/umts_rrc_asn_library/GPS-TOW-1msec.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-GPS-ReferenceTimeUncertainty.h"
#include "rf_phreaker/umts_rrc_asn_library/SFN-TOW-Uncertainty.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRAN-GPS-DriftRate.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UTRAN_GPSReferenceTime;
struct GPS_TOW_AssistList;

/* UE-Positioning-GPS-ReferenceTime-r7 */
typedef struct UE_Positioning_GPS_ReferenceTime_r7 {
	long	 gps_Week;
	GPS_TOW_1msec_t	 gps_tow_1msec;
	struct UTRAN_GPSReferenceTime	*utran_GPSReferenceTime	/* OPTIONAL */;
	UE_Positioning_GPS_ReferenceTimeUncertainty_t	*ue_Positioning_GPS_ReferenceTimeUncertainty	/* OPTIONAL */;
	SFN_TOW_Uncertainty_t	*sfn_tow_Uncertainty	/* OPTIONAL */;
	UTRAN_GPS_DriftRate_t	*utran_GPS_DriftRate	/* OPTIONAL */;
	struct GPS_TOW_AssistList	*gps_TOW_AssistList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_GPS_ReferenceTime_r7_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_GPS_ReferenceTime_r7;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UTRAN-GPSReferenceTime.h"
#include "rf_phreaker/umts_rrc_asn_library/GPS-TOW-AssistList.h"

#endif	/* _UE_Positioning_GPS_ReferenceTime_r7_H_ */
