/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UE_Positioning_OTDOA_AssistanceData_H_
#define	_UE_Positioning_OTDOA_AssistanceData_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_Positioning_OTDOA_ReferenceCellInfo;
struct UE_Positioning_OTDOA_NeighbourCellList;

/* UE-Positioning-OTDOA-AssistanceData */
typedef struct UE_Positioning_OTDOA_AssistanceData {
	struct UE_Positioning_OTDOA_ReferenceCellInfo	*ue_positioning_OTDOA_ReferenceCellInfo	/* OPTIONAL */;
	struct UE_Positioning_OTDOA_NeighbourCellList	*ue_positioning_OTDOA_NeighbourCellList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_OTDOA_AssistanceData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_OTDOA_AssistanceData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-OTDOA-ReferenceCellInfo.h"
#include "rf_phreaker/umts_rrc_asn_library/UE-Positioning-OTDOA-NeighbourCellList.h"

#endif	/* _UE_Positioning_OTDOA_AssistanceData_H_ */
