/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UE_Positioning_IPDL_Parameters_r4_H_
#define	_UE_Positioning_IPDL_Parameters_r4_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/IP-Spacing.h"
#include "rf_phreaker/umts_rrc_asn_library/IP-Length.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/IP-Spacing-TDD.h"
#include "rf_phreaker/umts_rrc_asn_library/IP-PCCPCH-r4.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR {
	UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR_fdd,
	UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR_tdd
} UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR;

/* Forward declarations */
struct BurstModeParameters;

/* UE-Positioning-IPDL-Parameters-r4 */
typedef struct UE_Positioning_IPDL_Parameters_r4 {
	struct UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo {
		UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_PR present;
		union UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo_u {
			struct UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo__fdd {
				IP_Spacing_t	 ip_Spacing;
				IP_Length_t	 ip_Length;
				long	 ip_Offset;
				long	 seed;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct UE_Positioning_IPDL_Parameters_r4__modeSpecificInfo__tdd {
				IP_Spacing_TDD_t	 ip_Spacing_TDD;
				long	 ip_slot;
				long	 ip_Start;
				IP_PCCPCH_r4_t	*ip_PCCPCG	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	struct BurstModeParameters	*burstModeParameters	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_Positioning_IPDL_Parameters_r4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Positioning_IPDL_Parameters_r4;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/BurstModeParameters.h"

#endif	/* _UE_Positioning_IPDL_Parameters_r4_H_ */
