/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UECapabilityInformation_H_
#define	_UECapabilityInformation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v370ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v380ext-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v3a0ext-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v4b0ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v590ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v5c0ext.h"
#include "rf_phreaker/umts_rrc_asn_library/UECapabilityInformation-v690ext-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UE_RadioAccessCapability;
struct InterRAT_UE_RadioAccessCapabilityList;

/* UECapabilityInformation */
typedef struct UECapabilityInformation {
	RRC_TransactionIdentifier_t	*rrc_TransactionIdentifier	/* OPTIONAL */;
	struct UE_RadioAccessCapability	*ue_RadioAccessCapability	/* OPTIONAL */;
	struct InterRAT_UE_RadioAccessCapabilityList	*ue_RATSpecificCapability	/* OPTIONAL */;
	struct UECapabilityInformation__v370NonCriticalExtensions {
		UECapabilityInformation_v370ext_t	 ueCapabilityInformation_v370ext;
		struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions {
			UECapabilityInformation_v380ext_IEs_t	 ueCapabilityInformation_v380ext;
			struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions {
				UECapabilityInformation_v3a0ext_IEs_t	 ueCapabilityInformation_v3a0ext;
				struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions {
					BIT_STRING_t	*ueCapabilityInformation_r3_add_ext	/* OPTIONAL */;
					struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtensions {
						UECapabilityInformation_v4b0ext_t	 ueCapabilityInformation_v4b0ext;
						struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions {
							UECapabilityInformation_v590ext_t	 ueCapabilityInformation_v590ext;
							struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions {
								UECapabilityInformation_v5c0ext_t	 ueCapabilityInformation_v5c0ext;
								struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions {
									UECapabilityInformation_v690ext_IEs_t	 ueCapabilityInformation_v690ext;
									struct UECapabilityInformation__v370NonCriticalExtensions__v380NonCriticalExtensions__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v4b0NonCriticalExtensions__v590NonCriticalExtensions__v5c0NonCriticalExtensions__v690NonCriticalExtensions__nonCriticalExtensions {
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *nonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v690NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v5c0NonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v590NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *v4b0NonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *laterNonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *v3a0NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *v380NonCriticalExtensions;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *v370NonCriticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UE-RadioAccessCapability.h"
#include "rf_phreaker/umts_rrc_asn_library/InterRAT-UE-RadioAccessCapabilityList.h"

#endif	/* _UECapabilityInformation_H_ */
