/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_DPCH_Info_r6_H_
#define	_UL_DPCH_Info_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/ScramblingCodeType.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-ScramblingCode.h"
#include "rf_phreaker/umts_rrc_asn_library/NumberOfDPDCH.h"
#include "rf_phreaker/umts_rrc_asn_library/SpreadingFactor.h"
#include <rf_phreaker/umts_rrc_asn_library/BOOLEAN.h>
#include "rf_phreaker/umts_rrc_asn_library/NumberOfFBI-Bits.h"
#include "rf_phreaker/umts_rrc_asn_library/PuncturingLimit.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_DPCH_Info_r6__modeSpecificInfo_PR {
	UL_DPCH_Info_r6__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UL_DPCH_Info_r6__modeSpecificInfo_PR_fdd,
	UL_DPCH_Info_r6__modeSpecificInfo_PR_tdd
} UL_DPCH_Info_r6__modeSpecificInfo_PR;
typedef enum UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR {
	UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR_NOTHING,	/* No components present */
	UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR_present,
	UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR_notPresent
} UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR;

/* Forward declarations */
struct UL_DPCH_PowerControlInfo_r6;
struct UL_TimingAdvanceControl_r4;
struct UL_CCTrCHList_r4;
struct UL_CCTrCHListToRemove;

/* UL-DPCH-Info-r6 */
typedef struct UL_DPCH_Info_r6 {
	struct UL_DPCH_PowerControlInfo_r6	*ul_DPCH_PowerControlInfo	/* OPTIONAL */;
	struct UL_DPCH_Info_r6__modeSpecificInfo {
		UL_DPCH_Info_r6__modeSpecificInfo_PR present;
		union UL_DPCH_Info_r6__modeSpecificInfo_u {
			struct UL_DPCH_Info_r6__modeSpecificInfo__fdd {
				ScramblingCodeType_t	 scramblingCodeType;
				UL_ScramblingCode_t	 scramblingCode;
				struct UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence {
					UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_PR present;
					union UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence_u {
						struct UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence__present {
							NumberOfDPDCH_t	*numberOfDPDCH	/* DEFAULT 1 */;
							SpreadingFactor_t	 spreadingFactor;
							BOOLEAN_t	 tfci_Existence;
							NumberOfFBI_Bits_t	*numberOfFBI_Bits	/* OPTIONAL */;
							PuncturingLimit_t	 puncturingLimit;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} present;
						struct UL_DPCH_Info_r6__modeSpecificInfo__fdd__dpdchPresence__notPresent {
							BOOLEAN_t	 tfci_Existence;
							NumberOfFBI_Bits_t	*numberOfFBI_Bits	/* OPTIONAL */;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} notPresent;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} dpdchPresence;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} fdd;
			struct UL_DPCH_Info_r6__modeSpecificInfo__tdd {
				struct UL_TimingAdvanceControl_r4	*ul_TimingAdvance	/* OPTIONAL */;
				struct UL_CCTrCHList_r4	*ul_CCTrCHList	/* OPTIONAL */;
				struct UL_CCTrCHListToRemove	*ul_CCTrCHListToRemove	/* OPTIONAL */;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_DPCH_Info_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_DPCH_Info_r6;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/UL-DPCH-PowerControlInfo-r6.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-TimingAdvanceControl-r4.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-CCTrCHList-r4.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-CCTrCHListToRemove.h"

#endif	/* _UL_DPCH_Info_r6_H_ */
