/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_LogicalChannelMapping_r6_H_
#define	_UL_LogicalChannelMapping_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MAC-LogicalChannelPriority.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-TransportChannelType.h"
#include "rf_phreaker/umts_rrc_asn_library/LogicalChannelIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/RLC-SizeExplicitList.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/E-DCH-MAC-d-FlowIdentity.h"
#include "rf_phreaker/umts_rrc_asn_library/DDI.h"
#include "rf_phreaker/umts_rrc_asn_library/RLC-PDU-SizeList.h"
#include <rf_phreaker/umts_rrc_asn_library/BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR {
	UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR_NOTHING,	/* No components present */
	UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR_dch_rach_usch,
	UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR_e_dch
} UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR;
typedef enum UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR {
	UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR_NOTHING,	/* No components present */
	UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR_allSizes,
	UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR_configured,
	UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR_explicitList
} UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR;

/* UL-LogicalChannelMapping-r6 */
typedef struct UL_LogicalChannelMapping_r6 {
	struct UL_LogicalChannelMapping_r6__ul_TrCH_Type {
		UL_LogicalChannelMapping_r6__ul_TrCH_Type_PR present;
		union UL_LogicalChannelMapping_r6__ul_TrCH_Type_u {
			struct UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch {
				UL_TransportChannelType_t	 ul_TransportChannelType;
				LogicalChannelIdentity_t	*logicalChannelIdentity	/* OPTIONAL */;
				struct UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList {
					UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_PR present;
					union UL_LogicalChannelMapping_r6__ul_TrCH_Type__dch_rach_usch__rlc_SizeList_u {
						NULL_t	 allSizes;
						NULL_t	 configured;
						RLC_SizeExplicitList_t	 explicitList;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} rlc_SizeList;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} dch_rach_usch;
			struct UL_LogicalChannelMapping_r6__ul_TrCH_Type__e_dch {
				LogicalChannelIdentity_t	 logicalChannelIdentity;
				E_DCH_MAC_d_FlowIdentity_t	 e_DCH_MAC_d_FlowIdentity;
				DDI_t	 ddi;
				RLC_PDU_SizeList_t	 rlc_PDU_SizeList;
				BOOLEAN_t	 includeInSchedulingInfo;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} e_dch;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ul_TrCH_Type;
	MAC_LogicalChannelPriority_t	 mac_LogicalChannelPriority;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_LogicalChannelMapping_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_LogicalChannelMapping_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_LogicalChannelMapping_r6_H_ */
