/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_MulticarrierEDCH_InfolistItem_TDD128_H_
#define	_UL_MulticarrierEDCH_InfolistItem_TDD128_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UARFCN.h"
#include <rf_phreaker/umts_rrc_asn_library/NativeInteger.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E_PUCH_Info_MulticarrierEDCH_TDD128;
struct E_AGCH_Information_TDD128;
struct E_HICH_Information_TDD128;

/* UL-MulticarrierEDCH-InfolistItem-TDD128 */
typedef struct UL_MulticarrierEDCH_InfolistItem_TDD128 {
	UARFCN_t	 uarfcn;
	long	 prxBASEdes;
	struct E_PUCH_Info_MulticarrierEDCH_TDD128	*e_PUCH_info	/* OPTIONAL */;
	struct E_AGCH_Information_TDD128	*e_AGCH_info	/* OPTIONAL */;
	struct E_HICH_Information_TDD128	*e_HICH_info	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_MulticarrierEDCH_InfolistItem_TDD128_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_MulticarrierEDCH_InfolistItem_TDD128;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "rf_phreaker/umts_rrc_asn_library/E-PUCH-Info-MulticarrierEDCH-TDD128.h"
#include "rf_phreaker/umts_rrc_asn_library/E-AGCH-Information-TDD128.h"
#include "rf_phreaker/umts_rrc_asn_library/E-HICH-Information-TDD128.h"

#endif	/* _UL_MulticarrierEDCH_InfolistItem_TDD128_H_ */
