/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "Class-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_SHCCH_MessageType_H_
#define	_UL_SHCCH_MessageType_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/PUSCHCapacityRequest.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_SHCCH_MessageType_PR {
	UL_SHCCH_MessageType_PR_NOTHING,	/* No components present */
	UL_SHCCH_MessageType_PR_puschCapacityRequest,
	UL_SHCCH_MessageType_PR_spare
} UL_SHCCH_MessageType_PR;

/* UL-SHCCH-MessageType */
typedef struct UL_SHCCH_MessageType {
	UL_SHCCH_MessageType_PR present;
	union UL_SHCCH_MessageType_u {
		PUSCHCapacityRequest_t	 puschCapacityRequest;
		NULL_t	 spare;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_SHCCH_MessageType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_SHCCH_MessageType;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_SHCCH_MessageType_H_ */
