/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_TransChCapability_H_
#define	_UL_TransChCapability_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/MaxNoBits.h"
#include "rf_phreaker/umts_rrc_asn_library/TurboSupport.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxSimultaneousTransChsUL.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxTransportBlocksUL.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxNumberOfTFC-UL.h"
#include "rf_phreaker/umts_rrc_asn_library/MaxNumberOfTF.h"
#include <rf_phreaker/umts_rrc_asn_library/NULL.h>
#include "rf_phreaker/umts_rrc_asn_library/MaxSimultaneousCCTrCH-Count.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_TransChCapability__modeSpecificInfo_PR {
	UL_TransChCapability__modeSpecificInfo_PR_NOTHING,	/* No components present */
	UL_TransChCapability__modeSpecificInfo_PR_fdd,
	UL_TransChCapability__modeSpecificInfo_PR_tdd
} UL_TransChCapability__modeSpecificInfo_PR;

/* UL-TransChCapability */
typedef struct UL_TransChCapability {
	MaxNoBits_t	 maxNoBitsTransmitted;
	MaxNoBits_t	 maxConvCodeBitsTransmitted;
	TurboSupport_t	 turboEncodingSupport;
	MaxSimultaneousTransChsUL_t	 maxSimultaneousTransChs;
	struct UL_TransChCapability__modeSpecificInfo {
		UL_TransChCapability__modeSpecificInfo_PR present;
		union UL_TransChCapability__modeSpecificInfo_u {
			NULL_t	 fdd;
			struct UL_TransChCapability__modeSpecificInfo__tdd {
				MaxSimultaneousCCTrCH_Count_t	 maxSimultaneousCCTrCH_Count;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} tdd;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} modeSpecificInfo;
	MaxTransportBlocksUL_t	 maxTransmittedBlocks;
	MaxNumberOfTFC_UL_t	 maxNumberOfTFC;
	MaxNumberOfTF_t	 maxNumberOfTF;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_TransChCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_TransChCapability;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_TransChCapability_H_ */
