/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UL_TransportChannelIdentity_r6_H_
#define	_UL_TransportChannelIdentity_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/E-DCH-MAC-d-FlowIdentity.h"
#include "rf_phreaker/umts_rrc_asn_library/UL-TrCH-Type.h"
#include "rf_phreaker/umts_rrc_asn_library/TransportChannelIdentity.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UL_TransportChannelIdentity_r6_PR {
	UL_TransportChannelIdentity_r6_PR_NOTHING,	/* No components present */
	UL_TransportChannelIdentity_r6_PR_dch_usch,
	UL_TransportChannelIdentity_r6_PR_e_dch
} UL_TransportChannelIdentity_r6_PR;

/* UL-TransportChannelIdentity-r6 */
typedef struct UL_TransportChannelIdentity_r6 {
	UL_TransportChannelIdentity_r6_PR present;
	union UL_TransportChannelIdentity_r6_u {
		struct UL_TransportChannelIdentity_r6__dch_usch {
			UL_TrCH_Type_t	 ul_TransportChannelType;
			TransportChannelIdentity_t	 ul_TransportChannelIdentity;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} dch_usch;
		E_DCH_MAC_d_FlowIdentity_t	 e_dch;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UL_TransportChannelIdentity_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UL_TransportChannelIdentity_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _UL_TransportChannelIdentity_r6_H_ */
