/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UM_RLC_OutOSeqDelivery_Info_r6_H_
#define	_UM_RLC_OutOSeqDelivery_Info_r6_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/TimerOSD-r6.h"
#include "rf_phreaker/umts_rrc_asn_library/WindowSizeOSD-r6.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UM-RLC-OutOSeqDelivery-Info-r6 */
typedef struct UM_RLC_OutOSeqDelivery_Info_r6 {
	TimerOSD_r6_t	*timer_OSD	/* OPTIONAL */;
	WindowSizeOSD_r6_t	 windowSize_OSD;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UM_RLC_OutOSeqDelivery_Info_r6_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UM_RLC_OutOSeqDelivery_Info_r6;

#ifdef __cplusplus
}
#endif

#endif	/* _UM_RLC_OutOSeqDelivery_Info_r6_H_ */
