/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU-definitions"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_UTRANMobilityInformation_H_
#define	_UTRANMobilityInformation_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-r3-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-v3a0ext-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/BIT_STRING.h>
#include "rf_phreaker/umts_rrc_asn_library/UtranMobilityInformation-v690ext-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-v860ext1-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_SEQUENCE.h>
#include "rf_phreaker/umts_rrc_asn_library/RRC-TransactionIdentifier.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-r5-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-r7-IEs.h"
#include "rf_phreaker/umts_rrc_asn_library/UTRANMobilityInformation-v860ext2-IEs.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UTRANMobilityInformation_PR {
	UTRANMobilityInformation_PR_NOTHING,	/* No components present */
	UTRANMobilityInformation_PR_r3,
	UTRANMobilityInformation_PR_later_than_r3
} UTRANMobilityInformation_PR;
typedef enum UTRANMobilityInformation__later_than_r3__criticalExtensions_PR {
	UTRANMobilityInformation__later_than_r3__criticalExtensions_PR_NOTHING,	/* No components present */
	UTRANMobilityInformation__later_than_r3__criticalExtensions_PR_r5,
	UTRANMobilityInformation__later_than_r3__criticalExtensions_PR_criticalExtensions
} UTRANMobilityInformation__later_than_r3__criticalExtensions_PR;
typedef enum UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR {
	UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR_NOTHING,	/* No components present */
	UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR_r7,
	UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR_criticalExtensions
} UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR;

/* UTRANMobilityInformation */
typedef struct UTRANMobilityInformation {
	UTRANMobilityInformation_PR present;
	union UTRANMobilityInformation_u {
		struct UTRANMobilityInformation__r3 {
			UTRANMobilityInformation_r3_IEs_t	 utranMobilityInformation_r3;
			struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions {
				UTRANMobilityInformation_v3a0ext_IEs_t	 utranMobilityInformation_v3a0ext;
				struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions {
					BIT_STRING_t	*utranMobilityInformation_r3_add_ext	/* OPTIONAL */;
					struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions {
						UtranMobilityInformation_v690ext_IEs_t	 utranMobilityInformation_v690ext;
						struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtentions {
							UTRANMobilityInformation_v860ext1_IEs_t	 utranMobilityInformation_v860ext;
							struct UTRANMobilityInformation__r3__v3a0NonCriticalExtensions__laterNonCriticalExtensions__v690NonCriticalExtensions__v860NonCriticalExtentions__nonCriticalExtensions {
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *nonCriticalExtensions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v860NonCriticalExtentions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *v690NonCriticalExtensions;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *laterNonCriticalExtensions;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *v3a0NonCriticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} r3;
		struct UTRANMobilityInformation__later_than_r3 {
			RRC_TransactionIdentifier_t	 rrc_TransactionIdentifier;
			struct UTRANMobilityInformation__later_than_r3__criticalExtensions {
				UTRANMobilityInformation__later_than_r3__criticalExtensions_PR present;
				union UTRANMobilityInformation__later_than_r3__criticalExtensions_u {
					struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5 {
						UTRANMobilityInformation_r5_IEs_t	 utranMobilityInformation_r5;
						struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions {
							UtranMobilityInformation_v690ext_IEs_t	 utranMobilityInformation_v690ext;
							struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions__v860NonCriticalExtentions {
								UTRANMobilityInformation_v860ext1_IEs_t	 utranMobilityInformation_v860ext;
								struct UTRANMobilityInformation__later_than_r3__criticalExtensions__r5__v690NonCriticalExtensions__v860NonCriticalExtentions__nonCriticalExtensions {
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *nonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} *v860NonCriticalExtentions;
							
							/* Context for parsing across buffer boundaries */
							asn_struct_ctx_t _asn_ctx;
						} *v690NonCriticalExtensions;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} r5;
					struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions {
						UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_PR present;
						union UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions_u {
							struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions__r7 {
								UTRANMobilityInformation_r7_IEs_t	 utranMobilityInformation_r7;
								BIT_STRING_t	*utranMobilityInformation_r7_add_ext	/* OPTIONAL */;
								struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions__r7__v860NonCriticalExtensions {
									UTRANMobilityInformation_v860ext2_IEs_t	 utranMobilityInformation_v860ext;
									struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions__r7__v860NonCriticalExtensions__nonCriticalExtensions {
										
										/* Context for parsing across buffer boundaries */
										asn_struct_ctx_t _asn_ctx;
									} *nonCriticalExtensions;
									
									/* Context for parsing across buffer boundaries */
									asn_struct_ctx_t _asn_ctx;
								} *v860NonCriticalExtensions;
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} r7;
							struct UTRANMobilityInformation__later_than_r3__criticalExtensions__criticalExtensions__criticalExtensions {
								
								/* Context for parsing across buffer boundaries */
								asn_struct_ctx_t _asn_ctx;
							} criticalExtensions;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} criticalExtensions;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensions;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} later_than_r3;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UTRANMobilityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UTRANMobilityInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _UTRANMobilityInformation_H_ */
