/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "InformationElements"
 * 	found in "rcc.txt"
 * 	`asn1c -S/skeletons -fnative-types -fcompound-names`
 */

#ifndef	_VelocityEstimate_H_
#define	_VelocityEstimate_H_


#include <rf_phreaker/umts_rrc_asn_library/asn_application.h>

/* Including external dependencies */
#include "rf_phreaker/umts_rrc_asn_library/HorizontalVelocity.h"
#include "rf_phreaker/umts_rrc_asn_library/HorizontalWithVerticalVelocity.h"
#include "rf_phreaker/umts_rrc_asn_library/HorizontalVelocityWithUncertainty.h"
#include "rf_phreaker/umts_rrc_asn_library/HorizontalWithVerticalVelocityAndUncertainty.h"
#include <rf_phreaker/umts_rrc_asn_library/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VelocityEstimate_PR {
	VelocityEstimate_PR_NOTHING,	/* No components present */
	VelocityEstimate_PR_horizontalVelocity,
	VelocityEstimate_PR_horizontalWithVerticalVelocity,
	VelocityEstimate_PR_horizontalVelocityWithUncertainty,
	VelocityEstimate_PR_horizontalWithVerticalVelocityAndUncertainty
} VelocityEstimate_PR;

/* VelocityEstimate */
typedef struct VelocityEstimate {
	VelocityEstimate_PR present;
	union VelocityEstimate_u {
		HorizontalVelocity_t	 horizontalVelocity;
		HorizontalWithVerticalVelocity_t	 horizontalWithVerticalVelocity;
		HorizontalVelocityWithUncertainty_t	 horizontalVelocityWithUncertainty;
		HorizontalWithVerticalVelocityAndUncertainty_t	 horizontalWithVerticalVelocityAndUncertainty;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VelocityEstimate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VelocityEstimate;

#ifdef __cplusplus
}
#endif

#endif	/* _VelocityEstimate_H_ */
